// Schema.voices.Add("Class", "Text", "Real Text.", "sound")

local function AddVoice(text, realtext, sound)
    Schema.voices.Add("Charger", text, realtext, sound)
end

AddVoice("MOVE IN", "Move in.", "triage-hl2rp/charger/advancing_on_target_01.wav")
AddVoice("MOVING1", "Moving now.", "triage-hl2rp/charger/advancing_on_target_02.wav")
AddVoice("MOVING2", "Pressing.", "triage-hl2rp/charger/advancing_on_target_03.wav")
AddVoice("APPROACHING1", "Approaching target.", "triage-hl2rp/charger/advancing_on_target_04.wav")
AddVoice("PRESSURE", "Pressure.", "triage-hl2rp/charger/advancing_on_target_05.wav")
AddVoice("MOVING3", "Proceeding on infected.", "triage-hl2rp/charger/advancing_on_target_06.wav")
AddVoice("MOVING4", "Forward steady.", "triage-hl2rp/charger/advancing_on_target_07.wav")
AddVoice("PUSHING1", "Pushing forward.", "triage-hl2rp/charger/advancing_on_target_08.wav")
AddVoice("MOVING5", "Wallhammer, moving.", "triage-hl2rp/charger/advancing_on_target_09.wav")
AddVoice("COPY MOVING", "Copy, moving on contaminant.", "triage-hl2rp/charger/advancing_on_target_10.wav")
AddVoice("PRESSURE2", "Pressure, pressure!", "triage-hl2rp/charger/advancing_on_target_11.wav")
AddVoice("PRESSURE3", "Stabalization teams, forward pressure.", "triage-hl2rp/charger/advancing_on_target_12.wav")
AddVoice("MOVING6", "Commencing on infected.", "triage-hl2rp/charger/advancing_on_target_13.wav")
AddVoice("PUSHING2", "Pushing.", "triage-hl2rp/charger/advancing_on_target_14.wav")
AddVoice("MOVING7", "Wallhammer is moving on infected.", "triage-hl2rp/charger/advancing_on_target_15.wav")
AddVoice("PUSHING3", "Wallhammer is pushing sector.", "triage-hl2rp/charger/advancing_on_target_16.wav")
AddVoice("APPROACHING2", "Approaching contaminant.", "triage-hl2rp/charger/advancing_on_target_17.wav")
AddVoice("ADVANCING1", "Wallhammer, advancing on target.", "triage-hl2rp/charger/advancing_on_target_18.wav")
AddVoice("ADVANCING2", "Wallhammer, advancing.", "triage-hl2rp/charger/advancing_on_target_19.wav")
AddVoice("PUSHING4", "Wallhammer, pushing.", "triage-hl2rp/charger/advancing_on_target_20.wav")
 
 
AddVoice("ATTACKING1", "Going sharp.", "triage-hl2rp/charger/announceattack_01.wav")
AddVoice("ATTACKING2", "Engaging.", "triage-hl2rp/charger/announceattack_02.wav")
AddVoice("ATTACKING3", "Target engaged.", "triage-hl2rp/charger/announceattack_03.wav")
AddVoice("PROSECUTING", "Prosecuting.", "triage-hl2rp/charger/announceattack_04.wav")
AddVoice("ATTACKING4", "Wallhammer, full active on hostile.", "triage-hl2rp/charger/announceattack_05.wav")
AddVoice("TAKING ADVANTAGE", "Taking advantage.", "triage-hl2rp/charger/announceattack_08.wav")
AddVoice("WEAPONS FREE2", "Target locked, daggers free.", "triage-hl2rp/charger/announceattack_09.wav")
AddVoice("WEAPONS FREE1", "Weapons free.", "triage-hl2rp/charger/announceattack_11.wav")
 
 
AddVoice("TARGET ONE", "Target-One.", "triage-hl2rp/charger/announceattack_alyx_01.wav")
AddVoice("STOP NOW", "Stop, now.", "triage-hl2rp/charger/announceattack_alyx_02.wav")
AddVoice("", "It's Alyx.", "triage-hl2rp/charger/announceattack_alyx_04.wav")
AddVoice("", "Alyx confirmed.", "triage-hl2rp/charger/announceattack_alyx_06.wav")
AddVoice("", "Daggers on Alyx.", "triage-hl2rp/charger/announceattack_alyx_07.wav")
AddVoice("WEAPONS FREE3", "Weapons free on Target-One.", "triage-hl2rp/charger/announceattack_alyx_08.wav")
AddVoice("FIRING PRIMARY", "Firing on primary hostile.", "triage-hl2rp/charger/announceattack_alyx_09.wav")
AddVoice("ITS HER", "It's her. Wallhammer, engaging.", "triage-hl2rp/charger/announceattack_alyx_10.wav")
AddVoice("CONFIRMED1", "Primary target confirmed.", "triage-hl2rp/charger/announceattack_alyx_11.wav")
 
 
AddVoice("BREAK COVER1", "Breaking cover.", "triage-hl2rp/charger/announceattack_cover_01.wav")
AddVoice("BREAK COVER2", "Code breakdown in sector.", "triage-hl2rp/charger/announceattack_cover_02.wav")
AddVoice("BREAK COVER3", "Designate target cover as shadow.", "triage-hl2rp/charger/announceattack_cover_03.wav")
AddVoice("BREAKING COVER IN", "Exposing hostile in three...", "triage-hl2rp/charger/announceattack_cover_04.wav")
AddVoice("BREAK COVER4", "Target is protected. Rectifying.", "triage-hl2rp/charger/announceattack_cover_05.wav")
AddVoice("BREAK COVER5", "Removing support.", "triage-hl2rp/charger/announceattack_cover_06.wav")
AddVoice("BREAK COVER6", "Daggers on cover.", "triage-hl2rp/charger/announceattack_cover_07.wav")
AddVoice("BREAK COVER7", "Full-active on target cover.", "triage-hl2rp/charger/announceattack_cover_08.wav")
AddVoice("BREAK COVER8", "Wallhammer, going sharp on cover.", "triage-hl2rp/charger/announceattack_cover_09.wav")
 
 
AddVoice("GRENADE OUT1", "Bouncer out.", "triage-hl2rp/charger/announceattack_grenade_01.wav")
AddVoice("GRENADE OUT2", "Grenade out.", "triage-hl2rp/charger/announceattack_grenade_02.wav")
AddVoice("GRENADE OUT3", "Extractor away.", "triage-hl2rp/charger/announceattack_grenade_03.wav")
AddVoice("GRENADE1", "Bouncer, bouncer!", "triage-hl2rp/charger/announceattack_grenade_04.wav")
AddVoice("GET DOWN", "Get down!", "triage-hl2rp/charger/announceattack_grenade_05.wav")
AddVoice("GRENADE IN", "Bouncer in three...", "triage-hl2rp/charger/announceattack_grenade_06.wav")
AddVoice("GRENADE OUT4", "Extracting.", "triage-hl2rp/charger/announceattack_grenade_07.wav")
AddVoice("GRENADE OUT5", "Deploying grenade.", "triage-hl2rp/charger/announceattack_grenade_08.wav")
AddVoice("STANDING BACK", "Standing back.", "triage-hl2rp/charger/announceattack_grenade_09.wav")
AddVoice("GRENADE OUT6", "Bouncer free.", "triage-hl2rp/charger/announceattack_grenade_10.wav")
 
 
AddVoice("ANTLION1", "Antlion.", "triage-hl2rp/charger/announceenemy_antlion_01.wav")
AddVoice("ANTLION2", "Target, antlion.", "triage-hl2rp/charger/announceenemy_antlion_02.wav")
AddVoice("ANTLION3", "Contact, antlion.", "triage-hl2rp/charger/announceenemy_antlion_03.wav")
AddVoice("ANTLION4", "Antlion incoming.", "triage-hl2rp/charger/announceenemy_antlion_04.wav")
AddVoice("ANTLION5", "Wallhammer, on antlion.", "triage-hl2rp/charger/announceenemy_antlion_06.wav")
AddVoice("ANTLION6", "Antlion. Wallhammer, engaging.", "triage-hl2rp/charger/announceenemy_antlion_07.wav")
AddVoice("ANTLION7", "Antlion. Sector.", "triage-hl2rp/charger/announceenemy_antlion_10.wav")
 
 
AddVoice("HEADCRAB1", "Parasitics.", "triage-hl2rp/charger/announceenemy_headcrabs_01.wav")
AddVoice("HEADCRAB2", "Contact, parasitics.", "triage-hl2rp/charger/announceenemy_headcrabs_02.wav")
AddVoice("HEADCRAB3", "Parasitics, inbound.", "triage-hl2rp/charger/announceenemy_headcrabs_03.wav")
AddVoice("HEADCRAB4", "Wallhammer, visual on parasitics.", "triage-hl2rp/charger/announceenemy_headcrabs_04.wav")
AddVoice("HEADCRAB5", "Viscon, parasitics.", "triage-hl2rp/charger/announceenemy_headcrabs_05.wav")
AddVoice("HEADCRAB6", "We've got parasitics over here.", "triage-hl2rp/charger/announceenemy_headcrabs_07.wav")
AddVoice("HEADCRAB7", "Live parasitics.", "triage-hl2rp/charger/announceenemy_headcrabs_08.wav")
AddVoice("HEADCRAB8", "Parasitic infestation confirmed.", "triage-hl2rp/charger/announceenemy_headcrabs_10.wav")
 
 
AddVoice("ZOMBIE1", "Necrotics.", "triage-hl2rp/charger/announceenemy_zombie_01.wav")
AddVoice("ZOMBIE2", "Necrotics inbound.", "triage-hl2rp/charger/announceenemy_zombie_02.wav")
AddVoice("ZOMBIE3", "Infestation confirmed.", "triage-hl2rp/charger/announceenemy_zombie_03.wav")
AddVoice("ZOMBIE4", "Wallhammer, visual on necrotics.", "triage-hl2rp/charger/announceenemy_zombie_04.wav")
AddVoice("ZOMBIE5", "Contact, necrotics.", "triage-hl2rp/charger/announceenemy_zombie_05.wav")
AddVoice("ZOMBIE6", "Sightlines on necrotics.", "triage-hl2rp/charger/announceenemy_zombie_06.wav")
AddVoice("ZOMBIE7", "Necrotics active.", "triage-hl2rp/charger/announceenemy_zombie_08.wav")
AddVoice("ZOMBIE8", "Viscon, necrotics.", "triage-hl2rp/charger/announceenemy_zombie_09.wav")
AddVoice("ZOMBIE9", "Necrotics here.", "triage-hl2rp/charger/announceenemy_zombie_10.wav")
 
 
AddVoice("DEAD1", "Hostile down.", "triage-hl2rp/charger/announcekill_01.wav")
AddVoice("DEAD2", "Target down.", "triage-hl2rp/charger/announcekill_02.wav")
AddVoice("DEAD3", "Kill confirmed.", "triage-hl2rp/charger/announcekill_03.wav")
AddVoice("DEAD4", "Clean kill.", "triage-hl2rp/charger/announcekill_04.wav")
AddVoice("DEAD5", "Another one down.", "triage-hl2rp/charger/announcekill_05.wav")
AddVoice("DEAD6", "That's it.", "triage-hl2rp/charger/announcekill_06.wav")
AddVoice("DEAD7", "Contact down.", "triage-hl2rp/charger/announcekill_09.wav")
AddVoice("DEAD8", "They're dead.", "triage-hl2rp/charger/announcekill_11.wav")
AddVoice("DEAD9", "Wallhammer, kill confirmed.", "triage-hl2rp/charger/announcekill_12.wav")
AddVoice("DEAD10", "Hostile neutralized.", "triage-hl2rp/charger/announcekill_13.wav")
AddVoice("DEAD11", "Ended.", "triage-hl2rp/charger/announcekill_14.wav")
AddVoice("DEAD12", "Hostile is over.", "triage-hl2rp/charger/announcekill_15.wav")
 
 
AddVoice("ANTLION DEAD1", "Virome down.", "triage-hl2rp/charger/announcekill_antlion_01.wav")
AddVoice("ANTLION DEAD2", "Cleaned.", "triage-hl2rp/charger/announcekill_antlion_02.wav")
AddVoice("ANTLION DEAD3", "Target sterilized.", "triage-hl2rp/charger/announcekill_antlion_03.wav")
AddVoice("ANTLION DEAD4", "Cleansed.", "triage-hl2rp/charger/announcekill_antlion_04.wav")
AddVoice("HEADCRAB DEAD9", "Parasitics contained.", "triage-hl2rp/charger/announcekill_antlion_05.wav")
 
 
AddVoice("HEADCRAB DEAD1", "One parasitic cleaned.", "triage-hl2rp/charger/announcekill_headcrab_01.wav")
AddVoice("HEADCRAB DEAD2", "Parasitic cleaned.", "triage-hl2rp/charger/announcekill_headcrab_02.wav")
AddVoice("HEADCRAB DEAD3", "That's one.", "triage-hl2rp/charger/announcekill_headcrab_03.wav")
AddVoice("HEADCRAB DEAD4", "Parasitic contained.", "triage-hl2rp/charger/announcekill_headcrab_04.wav")
AddVoice("HEADCRAB DEAD5", "Cleansed.", "triage-hl2rp/charger/announcekill_headcrab_05.wav")
AddVoice("GROSS", "Gross.", "triage-hl2rp/charger/announcekill_headcrab_06.wav")
AddVoice("HEADCRAB DEAD6", "Outbreak ineffective.", "triage-hl2rp/charger/announcekill_headcrab_07.wav")
AddVoice("HEADCRAB DEAD7", "Outbreak contained.", "triage-hl2rp/charger/announcekill_headcrab_08.wav")
AddVoice("HEADCRAB DEAD8", "One parasitic vacated.", "triage-hl2rp/charger/announcekill_headcrab_09.wav")
 
 
AddVoice("TARGET DEAD1", "HVT is contained.", "triage-hl2rp/charger/announcekill_player_01.wav")
AddVoice("TARGET DEAD2", "Ordinal, target one is quiet.", "triage-hl2rp/charger/announcekill_player_02.wav")
AddVoice("SHES DEAD", "She's ended.", "triage-hl2rp/charger/announcekill_player_03.wav")
AddVoice("", "Ordinal, Alyx is over.", "triage-hl2rp/charger/announcekill_player_04.wav")
AddVoice("", "Alyx secure.", "triage-hl2rp/charger/announcekill_player_05.wav")
AddVoice("", "Alyx delivered.", "triage-hl2rp/charger/announcekill_player_06.wav")
AddVoice("DEAD", "Dead.", "triage-hl2rp/charger/announcekill_player_07.wav")
AddVoice("ELIMINATED", "Eliminated.", "triage-hl2rp/charger/announcekill_player_08.wav")
 
 
AddVoice("ZOMBIE DEAD1", "Necro contained.", "triage-hl2rp/charger/announcekill_zombie_01.wav")
AddVoice("ZOMBIE DEAD2", "Necrotic contained.", "triage-hl2rp/charger/announcekill_zombie_02.wav")
AddVoice("ZOMBIE DEAD3", "Stay dead.", "triage-hl2rp/charger/announcekill_zombie_03.wav")
AddVoice("ZOMBIE DEAD4", "Necro down, in sector.", "triage-hl2rp/charger/announcekill_zombie_04.wav")
AddVoice("ZOMBIE DEAD5", "Necrotic eliminated.", "triage-hl2rp/charger/announcekill_zombie_05.wav")
AddVoice("ITS DEAD", "It's dead.", "triage-hl2rp/charger/announcekill_zombie_06.wav")
AddVoice("ZOMBIE DEAD6", "Cleanse successful.", "triage-hl2rp/charger/announcekill_zombie_07.wav")
 
 
AddVoice("ALPHA", "Alpha.", "triage-hl2rp/charger/calloutcode_alpha_01.wav")
AddVoice("AND", "And.", "triage-hl2rp/charger/calloutcode_and_01.wav")
AddVoice("BRAVO", "Bravo.", "triage-hl2rp/charger/calloutcode_bravo_01.wav")
AddVoice("CHARLIE", "Charlie.", "triage-hl2rp/charger/calloutcode_charlie_01.wav")
AddVoice("DELTA", "Delta.", "triage-hl2rp/charger/calloutcode_delta_01.wav")
AddVoice("DASH", "Dash.", "triage-hl2rp/charger/calloutcode_dash_01.wav")
AddVoice("ECHO", "Echo.", "triage-hl2rp/charger/calloutcode_echo_01.wav")
AddVoice("EIGHT", "Eight.", "triage-hl2rp/charger/calloutcode_eight_01.wav")
AddVoice("8", "Eight.", "triage-hl2rp/charger/calloutcode_eight_01.wav")
AddVoice("ELEVEN", "Eleven.", "triage-hl2rp/charger/calloutcode_eleven_01.wav")
AddVoice("11", "Eleven.", "triage-hl2rp/charger/calloutcode_eleven_01.wav")
AddVoice("FIFTY", "Fifty.", "triage-hl2rp/charger/calloutcode_fifty_01.wav")
AddVoice("50", "Fifty.", "triage-hl2rp/charger/calloutcode_fifty_01.wav")
AddVoice("FIVE", "Five.", "triage-hl2rp/charger/calloutcode_five_01.wav")
AddVoice("5", "Five.", "triage-hl2rp/charger/calloutcode_five_01.wav")
AddVoice("FOURTY", "Fourty.", "triage-hl2rp/charger/calloutcode_forty_01.wav")
AddVoice("FORTY", "Fourty.", "triage-hl2rp/charger/calloutcode_forty_01.wav")
AddVoice("40", "Fourty.", "triage-hl2rp/charger/calloutcode_forty_01.wav")
AddVoice("FOUR", "Four.", "triage-hl2rp/charger/calloutcode_four_01.wav")
AddVoice("4", "Four.", "triage-hl2rp/charger/calloutcode_four_01.wav")
AddVoice("HUNDRED", "Hundred.", "triage-hl2rp/charger/calloutcode_hundred_01.wav")
AddVoice("NINER", "Niner.", "triage-hl2rp/charger/calloutcode_niner_01.wav")
AddVoice("9", "Niner.", "triage-hl2rp/charger/calloutcode_niner_01.wav")
AddVoice("NULL", "Null.", "triage-hl2rp/charger/calloutcode_null_01.wav")
AddVoice("ONE", "One.", "triage-hl2rp/charger/calloutcode_one_01.wav")
AddVoice("1", "One.", "triage-hl2rp/charger/calloutcode_one_01.wav")
AddVoice("SECTOR", "Sector.", "triage-hl2rp/charger/calloutcode_sector_01.wav")
AddVoice("SEVEN", "Seven.", "triage-hl2rp/charger/calloutcode_seven_01.wav")
AddVoice("7", "Seven.", "triage-hl2rp/charger/calloutcode_seven_01.wav")
AddVoice("SEVENTY", "Seventy.", "triage-hl2rp/charger/calloutcode_seventy_01.wav")
AddVoice("70", "Seventy.", "triage-hl2rp/charger/calloutcode_seventy_01.wav")
AddVoice("SIX", "Six.", "triage-hl2rp/charger/calloutcode_six_01.wav")
AddVoice("6", "Six.", "triage-hl2rp/charger/calloutcode_six_01.wav")
AddVoice("SIXTY", "Sixty.", "triage-hl2rp/charger/calloutcode_sixty_01.wav")
AddVoice("60", "Sixty.", "triage-hl2rp/charger/calloutcode_sixty_01.wav")
AddVoice("TEN", "Ten.", "triage-hl2rp/charger/calloutcode_ten_01.wav")
AddVoice("10", "Ten.", "triage-hl2rp/charger/calloutcode_ten_01.wav")
AddVoice("THIRTY", "Thirty.", "triage-hl2rp/charger/calloutcode_thirty_01.wav")
AddVoice("30", "Thirty.", "triage-hl2rp/charger/calloutcode_thirty_01.wav")
AddVoice("THOUSAND", "Thousand.", "triage-hl2rp/charger/calloutcode_thousand_01.wav")
AddVoice("THREE", "Three.", "triage-hl2rp/charger/calloutcode_three_01.wav")
AddVoice("3", "Three.", "triage-hl2rp/charger/calloutcode_three_01.wav")
AddVoice("TWENTY", "Twenty.", "triage-hl2rp/charger/calloutcode_twenty_01.wav")
AddVoice("20", "Twenty.", "triage-hl2rp/charger/calloutcode_twenty_01.wav")
AddVoice("TWO", "Two.", "triage-hl2rp/charger/calloutcode_two_01.wav")
AddVoice("2", "Two.", "triage-hl2rp/charger/calloutcode_two_01.wav")
 
 
AddVoice("", "Alyx.", "triage-hl2rp/charger/calloutentity_alyx_01.wav")
AddVoice("ANTICITIZENS", "Anti-citizens.", "triage-hl2rp/charger/calloutentity_anticitizens_01.wav")
AddVoice("ANTLION", "Antlion.", "triage-hl2rp/charger/calloutentity_antlion_01.wav")
AddVoice("APF", "APF.", "triage-hl2rp/charger/calloutentity_apf_01.wav")
AddVoice("BLADEWALL", "Bladewall.", "triage-hl2rp/charger/calloutentity_bladewall_01.wav")
AddVoice("COWALL", "Co-wall.", "triage-hl2rp/charger/calloutentity_cowall_01.wav")
AddVoice("FRIENDLY", "Friendly.", "triage-hl2rp/charger/calloutentity_friendly_01.wav")
AddVoice("HAMMERWALL", "Hammerwall.", "triage-hl2rp/charger/calloutentity_hammerwall_01.wav")
AddVoice("HOSTILES", "Hostiles.", "triage-hl2rp/charger/calloutentity_hostiles_01.wav")
AddVoice("3 PARASITICS", "Three parasitics.", "triage-hl2rp/charger/calloutentity_manyparasitics_01.wav")
AddVoice("NECROTIC", "Necrotic.", "triage-hl2rp/charger/calloutentity_necrotic_01.wav")
AddVoice("PARASITIC", "Parasitic.", "triage-hl2rp/charger/calloutentity_parasitic_01.wav")
AddVoice("SAFEMAN", "Safeman.", "triage-hl2rp/charger/calloutentity_safeman_01.wav")
AddVoice("WALLHAMMER", "Wallhammer.", "triage-hl2rp/charger/calloutentity_wallhammer_01.wav")
 
AddVoice("ABOVE", "Above.", "triage-hl2rp/charger/calloutlocation_above_01.wav")
AddVoice("APARTMENT", "Apartment.", "triage-hl2rp/charger/calloutlocation_apartment_01.wav")
AddVoice("BARRELS", "Barrels.", "triage-hl2rp/charger/calloutlocation_barrells_01.wav")
AddVoice("BEHIND", "Behind.", "triage-hl2rp/charger/calloutlocation_behind_01.wav")
AddVoice("BELOW", "Below.", "triage-hl2rp/charger/calloutlocation_below_01.wav")
AddVoice("BRICKS", "Bricks.", "triage-hl2rp/charger/calloutlocation_bricks_01.wav")
AddVoice("BRIDGE", "Bridge.", "triage-hl2rp/charger/calloutlocation_bridge_01.wav")
AddVoice("BUILDING", "Building.", "triage-hl2rp/charger/calloutlocation_building_01.wav")
AddVoice("CAR", "Car.", "triage-hl2rp/charger/calloutlocation_car_01.wav")
AddVoice("CRANE", "Crane.", "triage-hl2rp/charger/calloutlocation_crane_01.wav")
AddVoice("DOOR", "Door.", "triage-hl2rp/charger/calloutlocation_door_01.wav")
AddVoice("ELEVATOR", "Elevator.", "triage-hl2rp/charger/calloutlocation_elevator_01.wav")
AddVoice("FRONT", "Front.", "triage-hl2rp/charger/calloutlocation_front_01.wav")
AddVoice("HUT", "Hut.", "triage-hl2rp/charger/calloutlocation_hut_01.wav")
AddVoice("PIPES", "Pipes.", "triage-hl2rp/charger/calloutlocation_pipes_01.wav")
AddVoice("SHACK", "Shack.", "triage-hl2rp/charger/calloutlocation_shack_01.wav")
AddVoice("TOILET", "Toilet.", "triage-hl2rp/charger/calloutlocation_toilet_01.wav")
AddVoice("TRAINCAR", "Traincar.", "triage-hl2rp/charger/calloutlocation_traincar_01.wav")
AddVoice("TRASH", "Trash.", "triage-hl2rp/charger/calloutlocation_trash_01.wav")
AddVoice("TRUCK", "Truck.", "triage-hl2rp/charger/calloutlocation_truck_01.wav")
AddVoice("TUNNEL", "Tunnel.", "triage-hl2rp/charger/calloutlocation_tunnel_01.wav")
AddVoice("VAN", "Van.", "triage-hl2rp/charger/calloutlocation_van_01.wav")
AddVoice("WHEELS", "Wheels.", "triage-hl2rp/charger/calloutlocation_wheels_01.wav")
AddVoice("WOODPILE", "Woodpile.", "triage-hl2rp/charger/calloutlocation_woodpile_01.wav")
 
 
AddVoice("STRIKING1", "Striking them.", "triage-hl2rp/charger/charging_01.wav")
AddVoice("STRIKING2", "Striking now.", "triage-hl2rp/charger/charging_02.wav")
AddVoice("STRIKING", "Striking.", "triage-hl2rp/charger/charging_03.wav")
AddVoice("STRIKE", "Strike.", "triage-hl2rp/charger/charging_04.wav")
AddVoice("YELL", "*Garbled Yelling*", "triage-hl2rp/charger/charging_05.wav")
AddVoice("STRIKING3", "Strike fast.", "triage-hl2rp/charger/charging_06.wav")
 
 
AddVoice("OW ACTIVE HOSTILES", "Overwatch, we have active hostiles. Advise preparations.", "triage-hl2rp/charger/combat_idle_012.wav")
AddVoice("TARGET ACTIVE", "Negative, target is still active.", "triage-hl2rp/charger/combat_idle_020.wav")
AddVoice("CON ALPHA", "Copy that. Forming condition ALPHA.", "triage-hl2rp/charger/combat_idle_030.wav")
AddVoice("CON ALPHA2", "Copy that. Forming condition ALPHA at GRID-NINER-DASH-THREE-SEVEN.", "triage-hl2rp/charger/combat_idle_031.wav")
AddVoice("HOLDING FOR", "Holding for advanced directive, over.", "triage-hl2rp/charger/combat_idle_040.wav")
AddVoice("RECALIBRATING", "Confirmed, recalibrating.", "triage-hl2rp/charger/combat_idle_050.wav")
AddVoice("SETTING UP", "Copy, setting up position.", "triage-hl2rp/charger/combat_idle_060.wav")
AddVoice("STILL ACTIVE", "They're still alive.", "triage-hl2rp/charger/combat_idle_070.wav")
AddVoice("CC UNDERWAY", "Copy that, contain and control is underway.", "triage-hl2rp/charger/combat_idle_080.wav")
AddVoice("RELOADING", "Reloading.", "triage-hl2rp/charger/combat_idle_090.wav")
AddVoice("LOCKED AND READY", "10-4, negative on dagger renew - locked and ready.", "triage-hl2rp/charger/combat_idle_100.wav")
AddVoice("TAC ADV", "Forming tactical advantage.", "triage-hl2rp/charger/combat_idle_110.wav")
AddVoice("STILL HOLDING", "Still holding.", "triage-hl2rp/charger/combat_idle_120.wav")
AddVoice("STILL HOLDING2", "Still holding.", "triage-hl2rp/charger/combat_idle_121.wav")
AddVoice("HOLDING BIODAT", "Holding for biodat upload.", "triage-hl2rp/charger/combat_idle_130.wav")
AddVoice("PREPARE SUNDOWN", "Prepare for sundown.", "triage-hl2rp/charger/combat_idle_140.wav")
AddVoice("PREPARING SUNDOWN", "Preparing for sundown.", "triage-hl2rp/charger/combat_idle_141.wav")
AddVoice("PREPARE COMMS", "Preparing comms for extended conflict.", "triage-hl2rp/charger/combat_idle_150.wav")
AddVoice("NO DAGGERS", "Negative, no daggers needed.", "triage-hl2rp/charger/combat_idle_160.wav")
AddVoice("EXTENDING", "Extending conflict duration.", "triage-hl2rp/charger/combat_idle_170.wav")
AddVoice("SCANNING BIODATS", "Scanning hostile biodats.", "triage-hl2rp/charger/combat_idle_180.wav")
AddVoice("DISREGARDING", "Disregarding last call.", "triage-hl2rp/charger/combat_idle_190.wav")
AddVoice("OW 10-9", "Overwatch, ten-niner.", "triage-hl2rp/charger/combat_idle_200.wav")
 
 
AddVoice("GRENADE3", "Evading.", "triage-hl2rp/charger/danger_grenade_01.wav")
AddVoice("GRENADE2", "Grenade!", "triage-hl2rp/charger/danger_grenade_02.wav")
AddVoice("TAKING COVER", "Taking cover.", "triage-hl2rp/charger/danger_grenade_03.wav")
AddVoice("GRENADE4", "Live grenade.", "triage-hl2rp/charger/danger_grenade_04.wav")
AddVoice("GRENADE5", "Audible bouncer, evading.", "triage-hl2rp/charger/danger_grenade_05.wav")
AddVoice("GRENADE6", "Grenade, move!", "triage-hl2rp/charger/danger_grenade_06.wav")
AddVoice("WALL UP", "Wall, up!", "triage-hl2rp/charger/danger_grenade_07.wav")
AddVoice("ALERT RADIALS", "Alert on radials.", "triage-hl2rp/charger/danger_grenade_08.wav")
AddVoice("STAND BACK WALL", "Standing back with wall.", "triage-hl2rp/charger/danger_grenade_09.wav")
AddVoice("GRENADE7", "Live bouncer!", "triage-hl2rp/charger/danger_grenade_10.wav")
 
 
AddVoice("LOF1", "Wallhammer, closing.", "triage-hl2rp/charger/establishinglof_01.wav")
AddVoice("LOF2", "Wallhammer, switching position.", "triage-hl2rp/charger/establishinglof_02.wav")
AddVoice("LOF3", "Maintain visuals.", "triage-hl2rp/charger/establishinglof_03.wav")
AddVoice("LOF4", "Holding sightlines.", "triage-hl2rp/charger/establishinglof_04.wav")
AddVoice("LOF5", "Realigning to hostile.", "triage-hl2rp/charger/establishinglof_05.wav")
AddVoice("LOF6", "Target visual confirmation.", "triage-hl2rp/charger/establishinglof_06.wav")
AddVoice("LOF7", "I'm marking sightlines.", "triage-hl2rp/charger/establishinglof_07.wav")
AddVoice("NO VISUAL", "No visual on target. Move!", "triage-hl2rp/charger/establishinglof_08.wav")
AddVoice("LOF8", "Realigning target delta.", "triage-hl2rp/charger/establishinglof_09.wav")
AddVoice("STAY THERE", "Stay there!", "triage-hl2rp/charger/establishinglof_10.wav")
AddVoice("CHANGING POS1", "Changing position.", "triage-hl2rp/charger/establishinglof_11.wav")
AddVoice("CHANGING POS2", "Optimizing location.", "triage-hl2rp/charger/establishinglof_12.wav")
AddVoice("CHANGING POS3", "Optimizing viscon.", "triage-hl2rp/charger/establishinglof_13.wav")
AddVoice("CHANGING POS4", "Problem visual, moving.", "triage-hl2rp/charger/establishinglof_14.wav")
AddVoice("CHANGING POS5", "Clearing sightlines.", "triage-hl2rp/charger/establishinglof_15.wav")
AddVoice("CHANGING POS6", "Forming sightlines.", "triage-hl2rp/charger/establishinglof_16.wav")
AddVoice("CONTACT IN", "Contact in three...", "triage-hl2rp/charger/establishinglof_17.wav")
AddVoice("EXPOSING", "Exposing target one.", "triage-hl2rp/charger/establishinglof_18.wav")
AddVoice("DONT MOVE", "Don't move.", "triage-hl2rp/charger/establishinglof_19.wav")
 
 
AddVoice("", "Alyx!", "triage-hl2rp/charger/fakeout_calltoalyx_01.wav")
AddVoice("", "Hey, Alyx!", "triage-hl2rp/charger/fakeout_calltoalyx_02.wav")
AddVoice("", "Hey Alyx, it's us!", "triage-hl2rp/charger/fakeout_calltoalyx_03.wav")
AddVoice("", "Alyx, you there?", "triage-hl2rp/charger/fakeout_calltoalyx_04.wav")
AddVoice("", "Alyx!", "triage-hl2rp/charger/fakeout_calltoalyx_05.wav")
 
 
AddVoice("TARGET FRIENDLY", "Cease fire, target is friendly.", "triage-hl2rp/charger/fakeout_responseceasefire_01.wav")
AddVoice("STANDING DOWN", "Hammer down, Wallhammer stepping down.", "triage-hl2rp/charger/fakeout_responseceasefire_02.wav")
AddVoice("CEASE FIRE", "Cease fire! No threat, no threat!", "triage-hl2rp/charger/fakeout_responseceasefire_03.wav")
AddVoice("", "Alyx is friendly.", "triage-hl2rp/charger/fakeout_responseceasefire_04.wav")
AddVoice("", "Stop fire! Alyx is friendly!", "triage-hl2rp/charger/fakeout_responseceasefire_05.wav")
 
 
AddVoice("HAHA", "Haha.", "triage-hl2rp/charger/fakeout_success_01.wav")
AddVoice("FRIEND GAME", "Friend game effective.", "triage-hl2rp/charger/fakeout_success_02.wav")
AddVoice("HOSTILE SCRAMBLED", "Hahaha... hostile is scrambled.", "triage-hl2rp/charger/fakeout_success_03.wav")
 
 
AddVoice("FIRING", "Firing.", "triage-hl2rp/charger/firing_01.wav")
AddVoice("FIRING2", "Engaging target.", "triage-hl2rp/charger/firing_02.wav")
AddVoice("FIRING3", "Wallhammer engaging.", "triage-hl2rp/charger/firing_03.wav")
AddVoice("WEAPONS FREE4", "Weapons free.", "triage-hl2rp/charger/firing_04.wav")
AddVoice("FIRING4", "Wallhammer, primary setpoint.", "triage-hl2rp/charger/firing_05.wav")
AddVoice("WEAPONS FREE5", "Open fire, weapons free.", "triage-hl2rp/charger/firing_06.wav")
AddVoice("WEAPONS FREE6", "Code Three, alter Delta.", "triage-hl2rp/charger/firing_07.wav")
AddVoice("FIRING5", "Cleaning sector.", "triage-hl2rp/charger/firing_08.wav")
AddVoice("FIRING6", "Committed.", "triage-hl2rp/charger/firing_09.wav")
AddVoice("WEAPONS FREE7", "Daggers free.", "triage-hl2rp/charger/firing_10.wav")
AddVoice("FIRING7", "Engaged and firing.", "triage-hl2rp/charger/firing_110.wav")
AddVoice("FIRING8", "Enforcing stability on primary target in sector.", "triage-hl2rp/charger/firing_120.wav")
AddVoice("FIRING9", "Target is in line.", "triage-hl2rp/charger/firing_130.wav")
AddVoice("FIRING10", "Target is in line and receiving spikes.", "triage-hl2rp/charger/firing_131.wav")
AddVoice("ESCALATING", "Escalating force on primary target.", "triage-hl2rp/charger/firing_140.wav")
AddVoice("GOING DOWN3", "They're going down.", "triage-hl2rp/charger/firing_150.wav")
AddVoice("GOING DOWN2", "They're going down.", "triage-hl2rp/charger/firing_151.wav")
AddVoice("GOING DOWN", "They're going down!", "triage-hl2rp/charger/firing_152.wav")
AddVoice("ALMOST OVER2", "Almost over.", "triage-hl2rp/charger/firing_160.wav")
AddVoice("ALMOST OVER", "It's almost over!", "triage-hl2rp/charger/firing_161.wav")
AddVoice("ALMOST OVER3", "It's almost over.", "triage-hl2rp/charger/firing_162.wav")
AddVoice("SENDING SPIKES", "Sending spikes.", "triage-hl2rp/charger/firing_170.wav")
AddVoice("SENDING SPIKES2", "Sending all spikes to primary target.", "triage-hl2rp/charger/firing_180.wav")
AddVoice("SENDING SPIKES3", "I'm sending all spikes.", "triage-hl2rp/charger/firing_190.wav")
AddVoice("DONT RESIST", "Don't resist.", "triage-hl2rp/charger/firing_200.wav")
AddVoice("WH ENGAGED", "Wallhammer, is engaged and firing.", "triage-hl2rp/charger/firing_210.wav")
AddVoice("ORDINAL FIRING", "Ordinal is engaged and firing.", "triage-hl2rp/charger/firing_220.wav")
AddVoice("APF FIRING", "APF is engaged and firing.", "triage-hl2rp/charger/firing_230.wav")
 
 
AddVoice("TARGET FIRE", "Open fire, priority one.", "triage-hl2rp/charger/firing_player_01.wav")
AddVoice("", "Opening fire on Alyx.", "triage-hl2rp/charger/firing_player_02.wav")
AddVoice("TARGET FIRE2", "Wallhammer, on prime target.", "triage-hl2rp/charger/firing_player_03.wav")
AddVoice("ORDINAL FIRE AT", "Ordinal, open fire at...", "triage-hl2rp/charger/firing_player_04.wav")
AddVoice("", "Daggers free on Vance.", "triage-hl2rp/charger/firing_player_05.wav")
 
 
AddVoice("FLASH FAIL", "Reflash in five.", "triage-hl2rp/charger/flash_failed_01.wav")
AddVoice("FLASH FAIL2", "Null flash, amend.", "triage-hl2rp/charger/flash_failed_03.wav")
AddVoice("FLASH FAIL3", "Requesting re-flash on target.", "triage-hl2rp/charger/flash_failed_05.wav")
AddVoice("FLASH FAIL4", "Blinder has failed.", "triage-hl2rp/charger/flash_failed_06.wav")
 
 
AddVoice("FLASHED", "Flash success, moving in.", "triage-hl2rp/charger/flash_success_01.wav")
AddVoice("FLASHED2", "Hostile is blinded.", "triage-hl2rp/charger/flash_success_03.wav")
AddVoice("FLASHED3", "Target has no visuals. Taking advantage.", "triage-hl2rp/charger/flash_success_04.wav")
AddVoice("FLASHED4", "Contaminant is scrambled.", "triage-hl2rp/charger/flash_success_05.wav")
AddVoice("FLASHED5", "Hostile is scrambled. All units, take advantage.", "triage-hl2rp/charger/flash_success_06.wav")
 
 
AddVoice("FLUSHING", "Clearing.", "triage-hl2rp/charger/flushing_01.wav")
AddVoice("FLUSHING2", "Distribution on three...", "triage-hl2rp/charger/flushing_02.wav")
AddVoice("FLUSHING3", "Wallhammer, flushing sector.", "triage-hl2rp/charger/flushing_03.wav")
AddVoice("EXTRACTING AT", "Wallhammer, extracting at...", "triage-hl2rp/charger/flushing_04.wav")
AddVoice("FLUSHING4", "Applying pressure. Flare down.", "triage-hl2rp/charger/flushing_05.wav")
AddVoice("FLUSHING5", "Extracting hostile at last known.", "triage-hl2rp/charger/flushing_06.wav")
AddVoice("FLUSHING6", "Bouncer, bouncer, on last known.", "triage-hl2rp/charger/flushing_07.wav")
 
 
AddVoice("DISPERSING", "Dispersing.", "triage-hl2rp/charger/getback_01.wav")
AddVoice("WALL UP COVER", "Wall up, taking cover.", "triage-hl2rp/charger/getback_02.wav")
AddVoice("GRENADE DOWN", "Grenade down.", "triage-hl2rp/charger/getback_03.wav")
AddVoice("BOUNCER", "Bouncer, bouncer.", "triage-hl2rp/charger/getback_04.wav")
AddVoice("EXTRACTOR", "Extractor down.", "triage-hl2rp/charger/getback_05.wav")
 
 
AddVoice("HEAR", "Audible, in sector.", "triage-hl2rp/charger/hear_suspicious_01.wav")
AddVoice("HEAR2", "Possible contaminant.", "triage-hl2rp/charger/hear_suspicious_02.wav")
AddVoice("HEAR3", "Possible hostile active.", "triage-hl2rp/charger/hear_suspicious_03.wav")
AddVoice("HEAR4", "Movement, at Wallhammer.", "triage-hl2rp/charger/hear_suspicious_04.wav")
AddVoice("SOUND ON", "Sound on.", "triage-hl2rp/charger/hear_suspicious_05.wav")
AddVoice("SOUND ON2", "Sound on, annnd reporting all contaminants.", "triage-hl2rp/charger/hear_suspicious_06.wav")
 
 
AddVoice("IDLE1", "Nothing to report, over.", "triage-hl2rp/charger/idle_01.wav")
AddVoice("IDLE2", "One, fourteen, three, six, eleven. Check. All clear on Echo-Four, over.", "triage-hl2rp/charger/idle_02.wav")
AddVoice("IDLE3", "Copy that. Sustaining viscon at sector NOMAD-KILO-THREE-DASH-SIX.", "triage-hl2rp/charger/idle_03.wav")
AddVoice("IDLE4", "Echo-One has negative movement. Grid SEVEN-DASH-TWO.", "triage-hl2rp/charger/idle_04.wav")
AddVoice("STANDING BY", "Affirmative. Standing by for opportunities.", "triage-hl2rp/charger/idle_05.wav")
AddVoice("TRANSMISSION CLEAR", "Transmission clear, radials clear, over.", "triage-hl2rp/charger/idle_06.wav")
AddVoice("REQUEST PROXY", "Overwatch, requesting proximity data on hostiles. Holding for transmission.", "triage-hl2rp/charger/idle_07.wav")
AddVoice("HOLDING TRANSMISSION", "Still holding for transmission, over.", "triage-hl2rp/charger/idle_08.wav")
AddVoice("SECTOR LOCKDOWN", "Overwatch is confirming sector lockdown. Keep sightlines open, and sound on.", "triage-hl2rp/charger/idle_09.wav")
AddVoice("IDLE5", "Affirmative, outbreak status is code DELTA-SEVEN. Team SUNDOWN is on contact overrun. Copy that.", "triage-hl2rp/charger/idle_10.wav")
AddVoice("IDLE6", "Negative... Copy that... No sector containment, no confirmation on target one vector... waiting for secondary parameter codes.", "triage-hl2rp/charger/idle_11.wav")
AddVoice("UPDATING BIODAT", "Updating biodat... Stimdose: Thirty-Two. Dagger: Seventy-Eight. Shield: One-Hundred. Biprox: Point-Seven-Three.. Audibles: Three. Lightvis: Fifteen. Over.", "triage-hl2rp/charger/idle_12.wav")
AddVoice("IDLE7", "Roger that. Setting viscerators in Apex-Five. We have biotics at the perimeter. Waiting for contact. Over.", "triage-hl2rp/charger/idle_13.wav")
AddVoice("NON TAGGED VIROMES", "Overwatch confirms non-tagged viromes inbound. All units advisory, prepare for contact.", "triage-hl2rp/charger/idle_14.wav")
AddVoice("IDLE8", "Callout code: DELTA-ECHO-SEVEN-NINER-ALPHA-TWO-WINDER-ZERO... confirmed.", "triage-hl2rp/charger/idle_15.wav")
AddVoice("STILL HERE", "Roger that. Still here.", "triage-hl2rp/charger/idle_16.wav")
AddVoice("COPY THAT2", "Copy that.", "triage-hl2rp/charger/idle_17.wav")
AddVoice("ACCEPT DISSONANCE UPDATE", "Copy, accepted. Updating cognitive suppression biodats. Update complete in t-minus three seconds. Dissonance resolved.", "triage-hl2rp/charger/idle_18.wav")
AddVoice("DISSONANCE UPDATE", "Overwatch is requesting all units refresh and resolve. Cognitive dissonance will not be tolerated. Negative... memories included. Update is live, acceptance is mandatory.", "triage-hl2rp/charger/idle_19.wav")
AddVoice("IDLE9", "Stablization team holding position. Lightvis at Seven-Three. Audibles at... Fifteen. Overwatch confirms HVT is perimeter inbound.", "triage-hl2rp/charger/idle_20.wav")
 
 
AddVoice("INJURED", "Requesting stimdose.", "triage-hl2rp/charger/injured_01.wav")
AddVoice("INJURED2", "Ordinal... I'm hit.", "triage-hl2rp/charger/injured_02.wav")
AddVoice("INJURED3", "Taking damage.", "triage-hl2rp/charger/injured_03.wav")
AddVoice("ASSIST", "Assist on Wallhammer!", "triage-hl2rp/charger/injured_04.wav")
AddVoice("INJURED4", "Wallhammer still active.", "triage-hl2rp/charger/injured_05.wav")
AddVoice("INJURED5", "Ineffective.", "triage-hl2rp/charger/injured_06.wav")
AddVoice("INJURED6", "Bodypacks holding.", "triage-hl2rp/charger/injured_07.wav")
 
 
AddVoice("HAHA2", "Haha.", "triage-hl2rp/charger/laugh_01.wav")
AddVoice("HAHA3", "Haha.", "triage-hl2rp/charger/laugh_02.wav")
AddVoice("HAHA4", "Haha.", "triage-hl2rp/charger/laugh_03.wav")
AddVoice("HAHA5", "Haha.", "triage-hl2rp/charger/laugh_04.wav")
AddVoice("HAHA6", "Haha.", "triage-hl2rp/charger/laugh_05.wav")
 
 
AddVoice("LOST ENEMY", "Contaminant not visible.", "triage-hl2rp/charger/lostenemy_01.wav")
AddVoice("GOD DAMNIT", "God damnit.", "triage-hl2rp/charger/lostenemy_02.wav")
AddVoice("REQUESTING LOCATION", "Requesting location.", "triage-hl2rp/charger/lostenemy_03.wav")
AddVoice("LOST ENEMY2", "Target lost.", "triage-hl2rp/charger/lostenemy_04.wav")
AddVoice("LOST ENEMY3", "Location assist, Wallhammer.", "triage-hl2rp/charger/lostenemy_05.wav")
AddVoice("LOST ENEMY4", "Hostile, visual, negative.", "triage-hl2rp/charger/lostenemy_06.wav")
AddVoice("LOST ENEMY5", "Lost sight. Contain.", "triage-hl2rp/charger/lostenemy_07.wav")
AddVoice("LOST ENEMY6", "No visual, Wallhammer.", "triage-hl2rp/charger/lostenemy_08.wav")
 
 
AddVoice("LOST VISUAL", "Missing hostile, sector unknown.", "triage-hl2rp/charger/lostvisual_01.wav")
AddVoice("LOST VISUAL2", "Wallhammer, requesting target location.", "triage-hl2rp/charger/lostvisual_02.wav")
AddVoice("REQUESTING LOCATION2", "Requesting location.", "triage-hl2rp/charger/lostvisual_03.wav")
AddVoice("LOST VISUAL3", "Lost sight of hostile.", "triage-hl2rp/charger/lostvisual_04.wav")
AddVoice("LOST VISUAL4", "Location assist on Wallhammer.", "triage-hl2rp/charger/lostvisual_05.wav")
AddVoice("LOST VISUAL5", "Need location assistance.", "triage-hl2rp/charger/lostvisual_07.wav")
AddVoice("NO VISUAL", "No visual.", "triage-hl2rp/charger/lostvisual_08.wav")
AddVoice("LOST VISUAL6", "Wallhammer, negative on visual.", "triage-hl2rp/charger/lostvisual_09.wav")
AddVoice("LOST VISUAL7", "Lost location, requesting hostile location.", "triage-hl2rp/charger/lostvisual_10.wav")
 
 
AddVoice("TARGET LOST", "Contaminant is quiet, requesting last known sector.", "triage-hl2rp/charger/lostvisual_player_01.wav")
AddVoice("VISUAL BLACKOUT", "We have total visual blackout.", "triage-hl2rp/charger/lostvisual_player_02.wav")
AddVoice("TARGET LOST2", "Hostile is quiet.", "triage-hl2rp/charger/lostvisual_player_03.wav")
AddVoice("TARGET LOST3", "Contaminant is evasive.", "triage-hl2rp/charger/lostvisual_player_04.wav")
AddVoice("CHECKING COVER", "Checking cover.", "triage-hl2rp/charger/lostvisual_player_05.wav")
AddVoice("CONTACT CHECK AT", "Contact check at...", "triage-hl2rp/charger/lostvisual_player_06.wav")
AddVoice("VISUALS LOST", "All visuals lost - eyes on.", "triage-hl2rp/charger/lostvisual_player_07.wav")
AddVoice("TARGET LOST4", "All contact quiet at Wallhammer. Requesting recon.", "triage-hl2rp/charger/lostvisual_player_08.wav")
 
 
AddVoice("PROXIMITY", "Proximity!", "triage-hl2rp/charger/nearpanic_02.wav")
AddVoice("PROXIMITY2", "Proximity threat, release!", "triage-hl2rp/charger/nearpanic_03.wav")
AddVoice("ASSIST2", "Assist, assist, assist!", "triage-hl2rp/charger/nearpanic_04.wav")
AddVoice("ASSIST3", "Wall assist, wall assist!", "triage-hl2rp/charger/nearpanic_05.wav")
AddVoice("BACK DOWN", "Back down, back down!", "triage-hl2rp/charger/nearpanic_07.wav")
 
 
AddVoice("COPY", "Copy.", "triage-hl2rp/charger/orderresponse_positive_01.wav")
AddVoice("ROGER", "Roger.", "triage-hl2rp/charger/orderresponse_positive_02.wav")
AddVoice("COPY THAT", "Copy that.", "triage-hl2rp/charger/orderresponse_positive_03.wav")
AddVoice("POSITIVE", "Positive.", "triage-hl2rp/charger/orderresponse_positive_04.wav")
AddVoice("PROCEEDING", "Proceeding.", "triage-hl2rp/charger/orderresponse_positive_05.wav")
AddVoice("AFFIRMATIVE", "Affirmative.", "triage-hl2rp/charger/orderresponse_positive_06.wav")
 
 
AddVoice("HOLDING", "Holding position.", "triage-hl2rp/charger/overwatch_01.wav")
AddVoice("LOCATION LOCKED", "Location locked.", "triage-hl2rp/charger/overwatch_02.wav")
AddVoice("WEAPONS READY", "Weapons ready.", "triage-hl2rp/charger/overwatch_03.wav")
AddVoice("VISCON LAST", "Viscon on last known position.", "triage-hl2rp/charger/overwatch_04.wav")
AddVoice("EYES LAST KNOWN", "Eyes on last known.", "triage-hl2rp/charger/overwatch_05.wav")
AddVoice("OBSERVING", "Observing.", "triage-hl2rp/charger/overwatch_06.wav")
AddVoice("IN POSITION", "Wallhammer, in position.", "triage-hl2rp/charger/overwatch_07.wav")
AddVoice("HOLDING2", "Holding focus.", "triage-hl2rp/charger/overwatch_08.wav")
AddVoice("STOP SOUND", "Stop sound, stop sound.", "triage-hl2rp/charger/overwatch_09.wav")
AddVoice("HOSTILE UNWILLING", "Hostile unwilling, stand by.", "triage-hl2rp/charger/overwatch_10.wav")
AddVoice("HOLD", "Hold.", "triage-hl2rp/charger/overwatch_11.wav")
AddVoice("WAITING CONTACT", "Waiting for contact.", "triage-hl2rp/charger/overwatch_12.wav")
AddVoice("EVALUATING", "Evaluating.", "triage-hl2rp/charger/overwatch_13.wav")
AddVoice("AWAITING", "Awaiting problem.", "triage-hl2rp/charger/overwatch_14.wav")
AddVoice("WAITING CONTAINMENT", "Waiting for containment.", "triage-hl2rp/charger/overwatch_15.wav")
AddVoice("HOLDING3", "Wallhammer, holding.", "triage-hl2rp/charger/overwatch_16.wav")
AddVoice("EYES ON", "Wallhammer, eyes on.", "triage-hl2rp/charger/overwatch_17.wav")
AddVoice("CONT LOCKED", "Contaminant is locked.", "triage-hl2rp/charger/overwatch_18.wav")
AddVoice("SECURING EDGE", "Wallhammer, securing edge.", "triage-hl2rp/charger/overwatch_19.wav")
AddVoice("CHECKING EDGES", "Checking all edges.", "triage-hl2rp/charger/overwatch_20.wav")
 
 
AddVoice("TARGET HURT", "Hostile is vulnerable.", "triage-hl2rp/charger/playerishurt_01.wav")
AddVoice("TARGET HURT2", "Target at odds.", "triage-hl2rp/charger/playerishurt_02.wav")
AddVoice("TARGET HURT3", "Target compromised.", "triage-hl2rp/charger/playerishurt_03.wav")
AddVoice("MOVE IN2", "Move in, move in!", "triage-hl2rp/charger/playerishurt_04.wav")
AddVoice("TARGET HURT4", "Contaminant at low value.", "triage-hl2rp/charger/playerishurt_05.wav")
AddVoice("TARGET HURT5", "Hostile is tagged.", "triage-hl2rp/charger/playerishurt_06.wav")
AddVoice("TARGET HURT6", "Recall on hostile.", "triage-hl2rp/charger/playerishurt_07.wav")
AddVoice("AMPLIFY WEAPONS", "Amplify weapons on Wallhammer.", "triage-hl2rp/charger/playerishurt_08.wav")
AddVoice("TARGET HURT7", "Red leak on hostile.", "triage-hl2rp/charger/playerishurt_09.wav")
AddVoice("TARGET HURT8", "Possible tag on prime.", "triage-hl2rp/charger/playerishurt_10.wav")
AddVoice("TARGET HURT9", "Hammer effective, at ZERO-NINER.", "triage-hl2rp/charger/playerishurt_11.wav")
AddVoice("ENDING TARGET", "Ending target one.", "triage-hl2rp/charger/playerishurt_13.wav")
 
 
AddVoice("BREACH READY", "Hammer ready!", "triage-hl2rp/charger/preparing_charge_01.wav")
AddVoice("BREACH READY2", "Preparing hammer.", "triage-hl2rp/charger/preparing_charge_02.wav")
AddVoice("BREACH READY3", "Hammer is ready to charge.", "triage-hl2rp/charger/preparing_charge_03.wav")
AddVoice("BREACHING", "Charging.", "triage-hl2rp/charger/preparing_charge_04.wav")
AddVoice("BREACHING AT", "Charging hammer at...", "triage-hl2rp/charger/preparing_charge_05.wav")
AddVoice("BREACHING COUNT", "Ready to hammer it in three... two... one.", "triage-hl2rp/charger/preparing_charge_06.wav")
 
 
AddVoice("WALL UP", "Wall up!", "triage-hl2rp/charger/preparing_shield_01.wav")
AddVoice("PREPARING WALL", "Preparing wall.", "triage-hl2rp/charger/preparing_shield_02.wav")
AddVoice("SHIELD UP", "Shield up.", "triage-hl2rp/charger/preparing_shield_03.wav")
AddVoice("RAISING WALL", "Raising wall.", "triage-hl2rp/charger/preparing_shield_04.wav")
AddVoice("WALL IS UP", "Wall is up.", "triage-hl2rp/charger/preparing_shield_05.wav")
AddVoice("WALL DEPLOYING IN", "Wall is ready to deploy in three... two... one.", "triage-hl2rp/charger/preparing_shield_06.wav")
 
 
AddVoice("SEARCH FINISHED", "All sectors scanned.", "triage-hl2rp/charger/reconnoiter_finish_01.wav")
AddVoice("SEARCH FINISHED2", "Contact is silent.", "triage-hl2rp/charger/reconnoiter_finish_02.wav")
AddVoice("CLEAR2", "Sector clear. Requesting stand by.", "triage-hl2rp/charger/reconnoiter_finish_03.wav")
AddVoice("CLEAR", "Area clear.", "triage-hl2rp/charger/reconnoiter_finish_04.wav")
AddVoice("HOSTILE SILENT", "Wallhammer reporting - hostile is silent.", "triage-hl2rp/charger/reconnoiter_finish_05.wav")
AddVoice("CLEAR3", "No contact.", "triage-hl2rp/charger/reconnoiter_finish_06.wav")
AddVoice("CLEAR4", "Arena secure.", "triage-hl2rp/charger/reconnoiter_finish_07.wav")
AddVoice("CLEAR5", "Looks clean.", "triage-hl2rp/charger/reconnoiter_finish_08.wav")
AddVoice("CONTACT LOST", "Contact lost, looks clear.", "triage-hl2rp/charger/reconnoiter_finish_09.wav")
AddVoice("NOTHING HERE", "Nothing here.", "triage-hl2rp/charger/reconnoiter_finish_10.wav")
AddVoice("STAYING SHARP", "Staying sharp, walls up.", "triage-hl2rp/charger/reconnoiter_finish_11.wav")
AddVoice("INEFFECTIVE CONTAMINANT", "Ineffective contaminant, requesting standdown.", "triage-hl2rp/charger/reconnoiter_finish_12.wav")
AddVoice("STANDBY BRAVO", "Standby for code bravo.", "triage-hl2rp/charger/reconnoiter_finish_13.wav")
AddVoice("NOTHING", "Nothing.", "triage-hl2rp/charger/reconnoiter_finish_14.wav")
AddVoice("CLEAR6", "Shadow clear.", "triage-hl2rp/charger/reconnoiter_finish_15.wav")
AddVoice("END SHADOW", "Request end on condition shadow.", "triage-hl2rp/charger/reconnoiter_finish_16.wav")
AddVoice("NOT HERE", "Not here.", "triage-hl2rp/charger/reconnoiter_finish_18.wav")
AddVoice("SEARCH FINISHED3", "Location clear. Recall assist.", "triage-hl2rp/charger/reconnoiter_finish_19.wav")
AddVoice("SEARCH FINISHED4", "All sectors clear. Recall.", "triage-hl2rp/charger/reconnoiter_finish_20.wav")
 
 
AddVoice("SEARCHING", "Processing viscon.", "triage-hl2rp/charger/reconnoiter_search_01.wav")
AddVoice("SEARCHING2", "Still searching.", "triage-hl2rp/charger/reconnoiter_search_02.wav")
AddVoice("SEARCHING3", "Still sweeping.", "triage-hl2rp/charger/reconnoiter_search_03.wav")
AddVoice("SEARCHING4", "Still scanning.", "triage-hl2rp/charger/reconnoiter_search_04.wav")
AddVoice("SEARCHING5", "Wallhammer, recon in progress.", "triage-hl2rp/charger/reconnoiter_search_05.wav")
AddVoice("SHADOW ACTIVE", "Condition shadow active.", "triage-hl2rp/charger/reconnoiter_search_06.wav")
AddVoice("SEARCHING6", "Recon in progress.", "triage-hl2rp/charger/reconnoiter_search_07.wav")
AddVoice("TARGET SHADOW", "Target is still shadow.", "triage-hl2rp/charger/reconnoiter_search_09.wav")
AddVoice("CLEAR MOVING", "Sector clear, advancing.", "triage-hl2rp/charger/reconnoiter_search_10.wav")
AddVoice("CLEAR MOVING2", "Null sector, proceeding.", "triage-hl2rp/charger/reconnoiter_search_11.wav")
AddVoice("CLEAR MOVING3", "Area cleaned, move in.", "triage-hl2rp/charger/reconnoiter_search_12.wav")
AddVoice("SEARCHING7", "Eyes still active.", "triage-hl2rp/charger/reconnoiter_search_13.wav")
AddVoice("NOTHING HERE2", "Nothing here.", "triage-hl2rp/charger/reconnoiter_search_14.wav")
AddVoice("HOSTILE QUIET", "Wallhammer reporting, hostile is still quiet.", "triage-hl2rp/charger/reconnoiter_search_15.wav")
AddVoice("SEARCHING COMPLETE", "Scanning complete. Resuming.", "triage-hl2rp/charger/reconnoiter_search_16.wav")
AddVoice("STILL NO VISUAL", "Still no visual.", "triage-hl2rp/charger/reconnoiter_search_17.wav")
AddVoice("RADIALS CLEAR", "Radials clear, resume.", "triage-hl2rp/charger/reconnoiter_search_18.wav")
 
 
AddVoice("SEARCH START", "Spreading out.", "triage-hl2rp/charger/reconnoiter_start_01.wav")
AddVoice("SEARCH START2", "Distributing.", "triage-hl2rp/charger/reconnoiter_start_03.wav")
AddVoice("SEARCH START3", "Wallhammer unit out.", "triage-hl2rp/charger/reconnoiter_start_04.wav")
AddVoice("SEARCH START4", "Deploying and scanning.", "triage-hl2rp/charger/reconnoiter_start_06.wav")
AddVoice("COMMENCING CLEANUP", "Commencing cleanup.", "triage-hl2rp/charger/reconnoiter_start_07.wav")
AddVoice("STAYING ALERT", "Staying alert.", "triage-hl2rp/charger/reconnoiter_start_08.wav")
AddVoice("SWEEPING HOSTILES", "Sweeping for hostiles.", "triage-hl2rp/charger/reconnoiter_start_09.wav")
AddVoice("SWEEPING CONTAMINANT", "Sweeping for contaminant.", "triage-hl2rp/charger/reconnoiter_start_10.wav")
AddVoice("SEARCH DAGGER", "Searching, condition dagger.", "triage-hl2rp/charger/reconnoiter_start_11.wav")
AddVoice("CLOSING ARENA", "Closing arena.", "triage-hl2rp/charger/reconnoiter_start_12.wav")
AddVoice("CONTAINMENT PROCEEDING", "Containment proceeding.", "triage-hl2rp/charger/reconnoiter_start_13.wav")
AddVoice("REPORTING SIGHTLINES", "Reporting sightlines.", "triage-hl2rp/charger/reconnoiter_start_14.wav")
AddVoice("FORM TARGET IN", "Formation on target in three...", "triage-hl2rp/charger/reconnoiter_start_15.wav")
AddVoice("PROCEED EXTRACTION", "Proceeding with hostile extraction.", "triage-hl2rp/charger/reconnoiter_start_16.wav")
AddVoice("INITIATE SHADOW", "Initiate condition shadow.", "triage-hl2rp/charger/reconnoiter_start_17.wav")
 
 
AddVoice("GOING SHARP2", "Going sharp, target delta.", "triage-hl2rp/charger/refindenemy_01.wav")
AddVoice("CONTACT", "Target contacted.", "triage-hl2rp/charger/refindenemy_02.wav")
AddVoice("CONTACT2", "Viscon, viscon, range!", "triage-hl2rp/charger/refindenemy_03.wav")
AddVoice("THERE", "There!", "triage-hl2rp/charger/refindenemy_04.wav")
AddVoice("CONTACT3", "Viscon, hostile found.", "triage-hl2rp/charger/refindenemy_05.wav")
AddVoice("OVER THERE", "Over there!", "triage-hl2rp/charger/refindenemy_06.wav")
AddVoice("MOVEMENT", "We have movement.", "triage-hl2rp/charger/refindenemy_07.wav")
AddVoice("REFIND", "Animal is back in the pit.", "triage-hl2rp/charger/refindenemy_08.wav")
AddVoice("CONTACT4", "Ready, hostile contact.", "triage-hl2rp/charger/refindenemy_09.wav")
AddVoice("REFIND2", "Hostile realigned in sector.", "triage-hl2rp/charger/refindenemy_10.wav")
AddVoice("REFIND3", "Wallhammer, recontact in sector.", "triage-hl2rp/charger/refindenemy_11.wav")
AddVoice("CONTACT5", "Hostile live, check radials.", "triage-hl2rp/charger/refindenemy_12.wav")
AddVoice("CONTACT6", "Additional sightlines confirmed.", "triage-hl2rp/charger/refindenemy_13.wav")
AddVoice("CONTACT7", "Sightlines confirmed on prime.", "triage-hl2rp/charger/refindenemy_14.wav")
AddVoice("INTERCEPTING", "Wallhammer intercepting.", "triage-hl2rp/charger/refindenemy_15.wav")
AddVoice("CONTACT CONFIRMED", "Location confirmed. Enforcing stability.", "triage-hl2rp/charger/refindenemy_16.wav")
AddVoice("VISCON IN 3", "Visual confirmation on three.", "triage-hl2rp/charger/refindenemy_17.wav")
AddVoice("ACTIVE VISUAL", "Active visual.", "triage-hl2rp/charger/refindenemy_18.wav")
 
 
AddVoice("RELOADING", "Reloading.", "triage-hl2rp/charger/reload_01.wav")
AddVoice("RELOADING2", "Refill on Wallhammer.", "triage-hl2rp/charger/reload_02.wav")
AddVoice("RELOADING3", "Wallhammer down on four... three... two... one.", "triage-hl2rp/charger/reload_03.wav")
AddVoice("RELOADING4", "Recharging.", "triage-hl2rp/charger/reload_05.wav")
AddVoice("RELOADING5", "Empty.", "triage-hl2rp/charger/reload_06.wav")
AddVoice("RELOADING6", "Empty on Wallhammer.", "triage-hl2rp/charger/reload_07.wav")
AddVoice("RELOADING7", "Provision low, reloading.", "triage-hl2rp/charger/reload_08.wav")
AddVoice("RELOADING8", "Hammer renew.", "triage-hl2rp/charger/reload_09.wav")
 
 
AddVoice("RETREAT", "Ripcord, ripcord!", "triage-hl2rp/charger/retreat_02.wav")
AddVoice("RETREAT2", "Ripcord on Wallhammer.", "triage-hl2rp/charger/retreat_03.wav")
AddVoice("RETREAT3", "Retreating.", "triage-hl2rp/charger/retreat_04.wav")
AddVoice("RETREAT4", "Falling back.", "triage-hl2rp/charger/retreat_05.wav")
AddVoice("RETREAT5", "Sector is too hot.", "triage-hl2rp/charger/retreat_06.wav")
AddVoice("RETREAT6", "Finding cover.", "triage-hl2rp/charger/retreat_07.wav")
AddVoice("RETREAT7", "Wallhammer, regroup.", "triage-hl2rp/charger/retreat_08.wav")
AddVoice("RETREAT8", "Sector volatile. Finding shade.", "triage-hl2rp/charger/retreat_10.wav")
 
 
AddVoice("MULTIPLE CONTACT", "Secondaries identified.", "triage-hl2rp/charger/sees_company_01.wav")
AddVoice("MULTIPLE CONTACT2", "Viscon on multiple unknowns.", "triage-hl2rp/charger/sees_company_02.wav")
AddVoice("MULTIPLE CONTACT3", "Viscon on secondaries.", "triage-hl2rp/charger/sees_company_03.wav")
AddVoice("MULTIPLE CONTACT4", "Checking silhouettes. Possible multipliers.", "triage-hl2rp/charger/sees_company_04.wav")
AddVoice("MULTIPLE CONTACT5", "We have multiple contaminants.", "triage-hl2rp/charger/sees_company_05.wav")
 
 
AddVoice("TARGET GRENADES", "Target-One has bouncers.", "triage-hl2rp/charger/sees_grenades_01.wav")
AddVoice("TARGET GRENADES2", "Hostile has bouncers. Be alert.", "triage-hl2rp/charger/sees_grenades_02.wav")
AddVoice("TARGET GRENADES3", "Contaminant has grenades. Disperse.", "triage-hl2rp/charger/sees_grenades_03.wav")
AddVoice("TARGET GRENADES4", "Primary target has extractors. Responder.", "triage-hl2rp/charger/sees_grenades_04.wav")
 
 
AddVoice("TARGET RELOADING", "Hostile reloading, hammer advantage.", "triage-hl2rp/charger/sees_reloading_01.wav")
AddVoice("TARGET RELOADING2", "Target is regen, open fire.", "triage-hl2rp/charger/sees_reloading_02.wav")
AddVoice("TARGET RELOADING3", "Taking advantage.", "triage-hl2rp/charger/sees_reloading_03.wav")
AddVoice("TARGET RELOADING4", "Contaminant is vulnerable.", "triage-hl2rp/charger/sees_reloading_04.wav")
AddVoice("", "Alyx reloading, full response active.", "triage-hl2rp/charger/sees_reloading_05.wav")
 
 
AddVoice("TARGET UPGRADES", "Spikes boosted on target one.", "triage-hl2rp/charger/sees_upgrades_01.wav")
AddVoice("TARGET UPGRADES2", "Overwatch, target one has boosters.", "triage-hl2rp/charger/sees_upgrades_02.wav")
AddVoice("TARGET UPGRADES3", "Hostile spikes are boosted.", "triage-hl2rp/charger/sees_upgrades_03.wav")
AddVoice("TARGET UPGRADES4", "Hostile has illegal spikes.", "triage-hl2rp/charger/sees_upgrades_04.wav")
AddVoice("TARGET UPGRADES5", "Boosters active on prime, respond with caution.", "triage-hl2rp/charger/sees_upgrades_05.wav")
 
 
AddVoice("MANDOWN", "Overwatch, request reserve action.", "triage-hl2rp/charger/squadmemberlost_01.wav")
AddVoice("MANDOWN2", "Overwatch, sector is not secure.", "triage-hl2rp/charger/squadmemberlost_02.wav")
AddVoice("MANDOWN3", "Outbreak in sector.", "triage-hl2rp/charger/squadmemberlost_03.wav")
AddVoice("MANDOWN4", "Overwatch, ground team is down, sector not controlled.", "triage-hl2rp/charger/squadmemberlost_05.wav")
AddVoice("MANDOWN5", "Overwatch, sector is overrun.", "triage-hl2rp/charger/squadmemberlost_06.wav")
AddVoice("MANDOWN6", "Overwatch, requesting SKYSHIELD.", "triage-hl2rp/charger/squadmemberlost_07.wav")
AddVoice("MANDOWN7", "Overwatch, recommend new formation.", "triage-hl2rp/charger/squadmemberlost_09.wav")
AddVoice("MANDOWN8", "Friendly is down.", "triage-hl2rp/charger/squadmemberlost_10.wav")
AddVoice("X IS QUIET", "...is quiet, requesting replacement", "triage-hl2rp/charger/squadmemberlost_11.wav")
 
 
AddVoice("LAST UNIT", "Overwatch, solo active.", "triage-hl2rp/charger/squadmemberlost_lastman_01.wav")
AddVoice("LAST UNIT2", "Overwatch, Wallhammer is last unit, requesting assist.", "triage-hl2rp/charger/squadmemberlost_lastman_02.wav")
AddVoice("LAST UNIT3", "Overwatch, requesting immediate shadow!", "triage-hl2rp/charger/squadmemberlost_lastman_03.wav")
AddVoice("LAST UNIT4", "Overwatch, outbreak is uncontained.", "triage-hl2rp/charger/squadmemberlost_lastman_04.wav")
AddVoice("", "", "triage-hl2rp/charger/squadmemberlost_lastman_05.wav")
AddVoice("LAST UNIT5", "Overwatch, solo contact on excessive hostiles.", "triage-hl2rp/charger/squadmemberlost_lastman_06.wav")
AddVoice("LAST UNIT6", "Survival mark deployed.", "triage-hl2rp/charger/squadmemberlost_lastman_07.wav")
AddVoice("LAST UNIT7", "Overwatch, requesting extraction on Wallhammer.", "triage-hl2rp/charger/squadmemberlost_lastman_08.wav")
AddVoice("LAST UNIT8", "Overwatch, be informed, Wallhammer is last responder.", "triage-hl2rp/charger/squadmemberlost_lastman_09.wav")
 
 
AddVoice("LEADER DOWN", "Overwatch, Ordinal is down.", "triage-hl2rp/charger/squadmemberlost_leader_01.wav")
AddVoice("LEADER DOWN2", "Ordinal is quiet, requesting new leader.", "triage-hl2rp/charger/squadmemberlost_leader_02.wav")
AddVoice("LEADER DOWN3", "Ordinal is condition SUNDOWN.", "triage-hl2rp/charger/squadmemberlost_leader_03.wav")
AddVoice("", "", "triage-hl2rp/charger/squadmemberlost_leader_04.wav")
AddVoice("LEADER DOWN4", "Overwatch, Ordinal is out. Respond.", "triage-hl2rp/charger/squadmemberlost_leader_05.wav")
AddVoice("LEADER DOWN5", "Ordinal silent, administer full response.", "triage-hl2rp/charger/squadmemberlost_leader_06.wav")
AddVoice("LEADER DOWN6", "Ordinal is flatline, Ordinal is flatline!", "triage-hl2rp/charger/squadmemberlost_leader_07.wav")
 
 
AddVoice("SWITCHING", "Switching.", "triage-hl2rp/charger/switching_weapons_01.wav")
AddVoice("SWITCHING2", "Swapping.", "triage-hl2rp/charger/switching_weapons_02.wav")
AddVoice("", "", "triage-hl2rp/charger/switching_weapons_03.wav")
 
 
AddVoice("SPIKES CLOSE", "Spikes close, no damage.", "triage-hl2rp/charger/takingfire_01.wav")
AddVoice("TAKING FIRE2", "Missed.", "triage-hl2rp/charger/takingfire_02.wav")
AddVoice("TAKING FIRE3", "Target error, take advantage.", "triage-hl2rp/charger/takingfire_03.wav")
AddVoice("TAKING FIRE4", "Hostile is inaccurate.", "triage-hl2rp/charger/takingfire_04.wav")
AddVoice("TAKING FIRE5", "Almost.", "triage-hl2rp/charger/takingfire_05.wav")
AddVoice("TAKING FIRE6", "Wallhammer is untouched.", "triage-hl2rp/charger/takingfire_06.wav")
AddVoice("TAKING FIRE7", "Missed again, taking advantage.", "triage-hl2rp/charger/takingfire_07.wav")
AddVoice("TAKING FIRE8", "Target has failed.", "triage-hl2rp/charger/takingfire_08.wav")
AddVoice("TAKING FIRE9", "Exercise advantage on hostile.", "triage-hl2rp/charger/takingfire_09.wav")
AddVoice("HOSTILE FAILED", "Hostile failed, reforming.", "triage-hl2rp/charger/takingfire_10.wav")
AddVoice("TAUNT", "Spikes ineffective. Target is unskilled.", "triage-hl2rp/charger/takingfire_11.wav")
 
 
AddVoice("TAUNT2", "Hostile is experiencing extreme panic.", "triage-hl2rp/charger/taunt_010.wav")
AddVoice("TAUNT3", "Hostile is overwhelmed.", "triage-hl2rp/charger/taunt_020.wav")
AddVoice("TAUNT4", "Target is at low motivation, take advantage.", "triage-hl2rp/charger/taunt_030.wav")
AddVoice("TAUNT5", "Target is at low motivation.", "triage-hl2rp/charger/taunt_031.wav")
AddVoice("YOU CAN COME OUT", "You can come out now!", "triage-hl2rp/charger/taunt_042.wav")
AddVoice("WE CAN HELP YOU2", "Attention hostile target, we can help you, it is safe.", "triage-hl2rp/charger/taunt_050.wav")
AddVoice("WE CAN HELP YOU", "We can help you, it is safe.", "triage-hl2rp/charger/taunt_051.wav")
AddVoice("TAUNT6", "Suspect is above legal aggression threshold. Taking advantage.", "triage-hl2rp/charger/taunt_060.wav")
AddVoice("ESCALATING2", "Proceeding with escalation.", "triage-hl2rp/charger/taunt_070.wav")
AddVoice("NON COMPLIANT", "Suspect is non-compliant with code 10-307.", "triage-hl2rp/charger/taunt_071.wav")
AddVoice("ESCALATING3", "Code 10-307, proceeding with escalation.", "triage-hl2rp/charger/taunt_072.wav")
AddVoice("TAUNT7", "Hostile is hesitating.", "triage-hl2rp/charger/taunt_081.wav")
AddVoice("TAUNT8", "Hostile attacks are ineffective, proceeding with containment.", "triage-hl2rp/charger/taunt_090.wav")
AddVoice("STANDING DOWN2", "Activating code 10-108, standing down.", "triage-hl2rp/charger/taunt_100.wav")
AddVoice("SUSPEND FIRE", "Suspend fire, target is friendly.", "triage-hl2rp/charger/taunt_111.wav")
AddVoice("STANDING DOWN3", "Standing down, code 10-40.", "triage-hl2rp/charger/taunt_120.wav")
AddVoice("CEASEFIRE ON TARGET", "Ceasing fire, target is non-hostile.", "triage-hl2rp/charger/taunt_131.wav")
AddVoice("DO NOT SHOOT", "Copy, do not shoot. Compliance confirmed.", "triage-hl2rp/charger/taunt_140.wav")
AddVoice("FRIENDLY2", "Target is friendly.", "triage-hl2rp/charger/taunt_150.wav")
AddVoice("FRIENDLY3", "Stand down, target is friendly.", "triage-hl2rp/charger/taunt_151.wav")
AddVoice("FRIENDLY4", "All units stand down, target is friendly.", "triage-hl2rp/charger/taunt_152.wav")
AddVoice("FRIENDLY5", "Friendly confirmed, cease fire.", "triage-hl2rp/charger/taunt_160.wav")
AddVoice("WAIT AND SEE2", "Overwatch, we have a wait and see at grid NINER-DASH-FIVE.", "triage-hl2rp/charger/taunt_170.wav")
AddVoice("WAIT AND SEE", "Overwatch, we have a wait and see.", "triage-hl2rp/charger/taunt_171.wav")
AddVoice("INJURED7", "Affirmative, target is low value.", "triage-hl2rp/charger/taunt_182.wav")
AddVoice("HOSTILE UNAWARE", "Copy that, hostile is unaware and ready for containment.", "triage-hl2rp/charger/taunt_191.wav")
AddVoice("INJURED8", "Hostile is showing fatigue. Prepare containment.", "triage-hl2rp/charger/taunt_200.wav")
 
 
AddVoice("NEGATIVE", "Negative.", "triage-hl2rp/charger/unabletocommence_01.wav")
AddVoice("NEGATORY", "Negatory.", "triage-hl2rp/charger/unabletocommence_02.wav")
AddVoice("NO", "No.", "triage-hl2rp/charger/unabletocommence_03.wav")
AddVoice("CANT COMPLY", "Can't comply.", "triage-hl2rp/charger/unabletocommence_04.wav")
AddVoice("DENIED", "Denied.", "triage-hl2rp/charger/unabletocommence_05.wav")
AddVoice("NEGATIVE2", "That's a negative.", "triage-hl2rp/charger/unabletocommence_06.wav")
AddVoice("CAN NOT EXECUTE", "Can not execute.", "triage-hl2rp/charger/unabletocommence_07.wav")
 
 
AddVoice("UNDERFIRE", "Spikes confirmation, wall up.", "triage-hl2rp/charger/underattack_01.wav")
AddVoice("UNDERFIRE2", "Hostile is live.", "triage-hl2rp/charger/underattack_02.wav")
AddVoice("UNDERFIRE3", "Contact!", "triage-hl2rp/charger/underattack_03.wav")
AddVoice("UNDERFIRE4", "Wallhammer, returing with pressure.", "triage-hl2rp/charger/underattack_04.wav")
AddVoice("UNDERFIRE5", "We have live contaminants.", "triage-hl2rp/charger/underattack_05.wav")
AddVoice("UNDERFIRE6", "Distribute.", "triage-hl2rp/charger/underattack_06.wav")
AddVoice("UNDERFIRE7", "Target is hostile, daggers free.", "triage-hl2rp/charger/underattack_07.wav")
AddVoice("UNDERFIRE8", "Hostile suppressing, responder on.", "triage-hl2rp/charger/underattack_08.wav")
AddVoice("UNDERFIRE9", "Overwatch, we have spikes.", "triage-hl2rp/charger/underattack_09.wav")
AddVoice("CONDITION DELTA", "Preparing condition delta.", "triage-hl2rp/charger/underattack_10.wav")
AddVoice("TAKING FIRE", "Taking fire.", "triage-hl2rp/charger/underattack_11.wav")
AddVoice("EXECUTING RESPONSE", "Executing full response.", "triage-hl2rp/charger/underattack_12.wav")
Schema.voices.AddClass("Charger", function(ply)
    local char = ply:GetCharacter()
    local class = char:GetClass()
    return (class == CLASS_OTA_CHARGER)
end)
