// Schema.voices.Add("Class", "Text", "Real Text.", "sound")

local function AddVoice(text, realtext, sound)
    Schema.voices.Add("Suppressor", text, realtext, sound)
end

AddVoice("MOVE IN", "Move in.", "triage-hl2rp/suppressor/advancing_on_target_01.wav")
AddVoice("MOVING1", "Moving now.", "triage-hl2rp/suppressor/advancing_on_target_02.wav")
AddVoice("MOVING2", "Pressing.", "triage-hl2rp/suppressor/advancing_on_target_03.wav")
AddVoice("APPROACHING1", "Approaching target.", "triage-hl2rp/suppressor/advancing_on_target_04.wav")
AddVoice("PRESSURE", "Pressure.", "triage-hl2rp/suppressor/advancing_on_target_05.wav")
AddVoice("MOVING3", "Proceeding on infected.", "triage-hl2rp/suppressor/advancing_on_target_06.wav")
AddVoice("MOVING4", "APF closing in..", "triage-hl2rp/suppressor/advancing_on_target_07.wav")
AddVoice("PUSHING1", "Pushing forward.", "triage-hl2rp/suppressor/advancing_on_target_08.wav")
AddVoice("MOVING5", "Sweeping in.", "triage-hl2rp/suppressor/advancing_on_target_09.wav")
AddVoice("COPY MOVING", "Moving on contaminant.", "triage-hl2rp/suppressor/advancing_on_target_10.wav")
AddVoice("PRESSURE2", "Pressure, pressure!", "triage-hl2rp/suppressor/advancing_on_target_11.wav")
AddVoice("PRESSURE3", "Stabalization teams, forward pressure.", "triage-hl2rp/suppressor/advancing_on_target_12.wav")
AddVoice("MOVING6", "Commencing on infected.", "triage-hl2rp/suppressor/advancing_on_target_13.wav")
AddVoice("PUSHING2", "Pushing.", "triage-hl2rp/suppressor/advancing_on_target_14.wav")
AddVoice("MOVING7", "Stablization Team has sector ID and is moving on infected.", "triage-hl2rp/suppressor/advancing_on_target_15.wav")
AddVoice("APF INBOUND", "APF unit is inbound.", "triage-hl2rp/suppressor/advancing_on_target_16.wav")
AddVoice("APPROACHING2", "Approaching contaminant.", "triage-hl2rp/suppressor/advancing_on_target_17.wav")
AddVoice("ADVANCING1", "APF, advancing on target.", "triage-hl2rp/suppressor/advancing_on_target_18.wav")
AddVoice("ADVANCING2", "APF, advancing.", "triage-hl2rp/suppressor/advancing_on_target_19.wav")
AddVoice("PUSHING4", "APF, pushing.", "triage-hl2rp/suppressor/advancing_on_target_20.wav")
 
 
AddVoice("ATTACKING1", "Going sharp.", "triage-hl2rp/suppressor/announceattack_01.wav")
AddVoice("ATTACKING2", "Engaging.", "triage-hl2rp/suppressor/announceattack_02.wav")
AddVoice("ATTACKING3", "Target engaged.", "triage-hl2rp/suppressor/announceattack_03.wav")
AddVoice("ATTACKING5", "APF suppressing.", "triage-hl2rp/suppressor/announceattack_04.wav")
AddVoice("ATTACKING4", "APF engaging.", "triage-hl2rp/suppressor/announceattack_05.wav")
AddVoice("ATTACKING6", "Execute full response.", "triage-hl2rp/suppressor/announceattack_06.wav")
AddVoice("TAKING ADVANTAGE", "Taking advantage.", "triage-hl2rp/suppressor/announceattack_08.wav")
AddVoice("WEAPONS FREE2", "Target locked, dagger out.", "triage-hl2rp/suppressor/announceattack_09.wav")
 
 
AddVoice("TARGET ONE", "Oppressing target one.", "triage-hl2rp/suppressor/announceattack_alyx_01.wav")
AddVoice("", "Disinfecting primary target.", "triage-hl2rp/suppressor/announceattack_alyx_02.wav")
AddVoice("", "", "triage-hl2rp/suppressor/announceattack_alyx_04.wav")
AddVoice("", "", "triage-hl2rp/suppressor/announceattack_alyx_06.wav")
AddVoice("", "", "triage-hl2rp/suppressor/announceattack_alyx_07.wav")
AddVoice("", "Weapons free on Target-One.", "triage-hl2rp/suppressor/announceattack_alyx_08.wav")
AddVoice("", "", "triage-hl2rp/suppressor/announceattack_alyx_09.wav")
AddVoice("", "Engaging target one.", "triage-hl2rp/suppressor/announceattack_alyx_10.wav")
AddVoice("CONFIRMED1", "Primary confirmed.", "triage-hl2rp/suppressor/announceattack_alyx_11.wav")
 
 
AddVoice("BREAK COVER1", "Breaking cover.", "triage-hl2rp/suppressor/announceattack_cover_01.wav")
AddVoice("BREAK COVER2", "Engaging target. Code breakdown.", "triage-hl2rp/suppressor/announceattack_cover_02.wav")
AddVoice("BREAK COVER3", "Designate target cover as shadow.", "triage-hl2rp/suppressor/announceattack_cover_03.wav")
AddVoice("BREAKING COVER IN", "Exposing hostile in three...", "triage-hl2rp/suppressor/announceattack_cover_04.wav")
AddVoice("BREAK COVER4", "Target is protected. Rectifying.", "triage-hl2rp/suppressor/announceattack_cover_05.wav")
AddVoice("BREAK COVER5", "APF, removing support.", "triage-hl2rp/suppressor/announceattack_cover_06.wav")
AddVoice("BREAK COVER6", "APF, daggers on cover.", "triage-hl2rp/suppressor/announceattack_cover_07.wav")
AddVoice("BREAK COVER7", "Full-active on target cover.", "triage-hl2rp/suppressor/announceattack_cover_08.wav")
AddVoice("BREAK COVER8", "Going sharp on cover.", "triage-hl2rp/suppressor/announceattack_cover_09.wav")
 
 
AddVoice("GRENADE OUT1", "Bouncer out.", "triage-hl2rp/suppressor/announceattack_grenade_01.wav")
AddVoice("GRENADE OUT2", "Grenade out.", "triage-hl2rp/suppressor/announceattack_grenade_02.wav")
AddVoice("GRENADE OUT3", "Extractor away.", "triage-hl2rp/suppressor/announceattack_grenade_03.wav")
AddVoice("GRENADE1", "Bouncer, bouncer!", "triage-hl2rp/suppressor/announceattack_grenade_04.wav")
AddVoice("GET DOWN", "Get down!", "triage-hl2rp/suppressor/announceattack_grenade_05.wav")
AddVoice("GRENADE IN", "Bouncer on three...", "triage-hl2rp/suppressor/announceattack_grenade_06.wav")
AddVoice("GRENADE OUT4", "Extracting.", "triage-hl2rp/suppressor/announceattack_grenade_07.wav")
AddVoice("GRENADE OUT5", "Deploying grenade.", "triage-hl2rp/suppressor/announceattack_grenade_08.wav")
AddVoice("STANDING BACK", "Standing back.", "triage-hl2rp/suppressor/announceattack_grenade_09.wav")
AddVoice("GRENADE OUT6", "Bouncer free.", "triage-hl2rp/suppressor/announceattack_grenade_10.wav")
 
 
AddVoice("ANTLION1", "Antlion.", "triage-hl2rp/suppressor/announceenemy_antlion_01.wav")
AddVoice("ANTLION2", "Target, antlion.", "triage-hl2rp/suppressor/announceenemy_antlion_02.wav")
AddVoice("ANTLION3", "Contact, antlion.", "triage-hl2rp/suppressor/announceenemy_antlion_03.wav")
AddVoice("ANTLION4", "Antlion incoming.", "triage-hl2rp/suppressor/announceenemy_antlion_04.wav")
AddVoice("ANTLION7", "Contact, antlion.", "triage-hl2rp/suppressor/announceenemy_antlion_05.wav")
AddVoice("ANTLION5", "APF, viscon on antlion.", "triage-hl2rp/suppressor/announceenemy_antlion_06.wav")
AddVoice("ANTLION6", "Antlion, APF engage!", "triage-hl2rp/suppressor/announceenemy_antlion_07.wav")
 
 
AddVoice("HEADCRAB1", "Parasitics.", "triage-hl2rp/suppressor/announceenemy_headcrabs_01.wav")
AddVoice("HEADCRAB2", "Call contact, parasitics.", "triage-hl2rp/suppressor/announceenemy_headcrabs_02.wav")
AddVoice("HEADCRAB3", "Parasitics, inbound.", "triage-hl2rp/suppressor/announceenemy_headcrabs_03.wav")
AddVoice("HEADCRAB4", "APF, visual on parasitics.", "triage-hl2rp/suppressor/announceenemy_headcrabs_04.wav")
AddVoice("HEADCRAB5", "Contact, parasitics.", "triage-hl2rp/suppressor/announceenemy_headcrabs_05.wav")
AddVoice("HEADCRAB6", "We've got parasitics over here.", "triage-hl2rp/suppressor/announceenemy_headcrabs_07.wav")
AddVoice("HEADCRAB7", "Live parasitics at sector.", "triage-hl2rp/suppressor/announceenemy_headcrabs_08.wav")
AddVoice("HEADCRAB8", "Parasitic infestation confirmed.", "triage-hl2rp/suppressor/announceenemy_headcrabs_10.wav")
 
 
AddVoice("ZOMBIE1", "Necrotics.", "triage-hl2rp/suppressor/announceenemy_zombie_01.wav")
AddVoice("ZOMBIE2", "Necrotics inbound.", "triage-hl2rp/suppressor/announceenemy_zombie_02.wav")
AddVoice("ZOMBIE3", "Infestation alert.", "triage-hl2rp/suppressor/announceenemy_zombie_03.wav")
AddVoice("ZOMBIE4", "APF, visual on necrotics.", "triage-hl2rp/suppressor/announceenemy_zombie_04.wav")
AddVoice("ZOMBIE5", "Contact, necrotics.", "triage-hl2rp/suppressor/announceenemy_zombie_05.wav")
AddVoice("ZOMBIE7", "Necrotics active.", "triage-hl2rp/suppressor/announceenemy_zombie_08.wav")
AddVoice("ZOMBIE8", "Necrotics, viscon.", "triage-hl2rp/suppressor/announceenemy_zombie_09.wav")
AddVoice("ZOMBIE9", "Necrotics here.", "triage-hl2rp/suppressor/announceenemy_zombie_10.wav")
 
 
AddVoice("DEAD1", "Hostile down.", "triage-hl2rp/suppressor/announcekill_01.wav")
AddVoice("DEAD2", "Target down.", "triage-hl2rp/suppressor/announcekill_02.wav")
AddVoice("DEAD3", "Kill confirmed.", "triage-hl2rp/suppressor/announcekill_03.wav")
AddVoice("DEAD4", "Clean kill.", "triage-hl2rp/suppressor/announcekill_04.wav")
AddVoice("DEAD5", "Another one down.", "triage-hl2rp/suppressor/announcekill_05.wav")
AddVoice("DEAD6", "That's it.", "triage-hl2rp/suppressor/announcekill_06.wav")
AddVoice("DEAD7", "Contact down.", "triage-hl2rp/suppressor/announcekill_09.wav")
AddVoice("DEAD8", "Hostile is silent.", "triage-hl2rp/suppressor/announcekill_11.wav")
AddVoice("DEAD9", "APF confirming kill.", "triage-hl2rp/suppressor/announcekill_12.wav")
AddVoice("DEAD10", "Hostile neutralized.", "triage-hl2rp/suppressor/announcekill_13.wav")
AddVoice("DEAD11", "It's done.", "triage-hl2rp/suppressor/announcekill_14.wav")
AddVoice("DEAD12", "Hostile is over.", "triage-hl2rp/suppressor/announcekill_15.wav")
 
 
AddVoice("ANTLION DEAD1", "Virome down.", "triage-hl2rp/suppressor/announcekill_antlion_01.wav")
AddVoice("ANTLION DEAD2", "Cleaned.", "triage-hl2rp/suppressor/announcekill_antlion_02.wav")
AddVoice("ANTLION DEAD3", "Target sterilized.", "triage-hl2rp/suppressor/announcekill_antlion_03.wav")
AddVoice("ANTLION DEAD4", "Cleaned.", "triage-hl2rp/suppressor/announcekill_antlion_04.wav")
AddVoice("HEADCRAB DEAD9", "Parasitics contained.", "triage-hl2rp/suppressor/announcekill_antlion_05.wav")
 
 
AddVoice("HEADCRAB DEAD1", "Clean.", "triage-hl2rp/suppressor/announcekill_headcrab_01.wav")
AddVoice("HEADCRAB DEAD2", "Sector clean.", "triage-hl2rp/suppressor/announcekill_headcrab_02.wav")
AddVoice("HEADCRAB DEAD3", "That's one.", "triage-hl2rp/suppressor/announcekill_headcrab_03.wav")
AddVoice("HEADCRAB DEAD4", "Contaminant contained.", "triage-hl2rp/suppressor/announcekill_headcrab_04.wav")
AddVoice("HEADCRAB DEAD5", "Cleaned.", "triage-hl2rp/suppressor/announcekill_headcrab_05.wav")
AddVoice("HEADCRAB DEAD6", "Outbreak ineffective.", "triage-hl2rp/suppressor/announcekill_headcrab_07.wav")
AddVoice("HEADCRAB DEAD7", "Outbreak contained.", "triage-hl2rp/suppressor/announcekill_headcrab_08.wav")
AddVoice("HEADCRAB DEAD8", "Parasitic vacated.", "triage-hl2rp/suppressor/announcekill_headcrab_09.wav")
 
 
AddVoice("TARGET DEAD1", "HVT is contained.", "triage-hl2rp/suppressor/announcekill_player_01.wav")
AddVoice("TARGET DEAD2", "Ordinal, target one is quiet.", "triage-hl2rp/suppressor/announcekill_player_02.wav")
AddVoice("SHES QUIET", "She's quiet.", "triage-hl2rp/suppressor/announcekill_player_03.wav")
AddVoice("", "Ordinal, Alyx is over.", "triage-hl2rp/suppressor/announcekill_player_04.wav")
AddVoice("", "Alyx secure.", "triage-hl2rp/suppressor/announcekill_player_05.wav")
AddVoice("", "Alyx delivered.", "triage-hl2rp/suppressor/announcekill_player_06.wav")
AddVoice("ELIMINATED", "Problem eliminated.", "triage-hl2rp/suppressor/announcekill_player_08.wav")
 
 
AddVoice("ZOMBIE DEAD1", "Necro contained.", "triage-hl2rp/suppressor/announcekill_zombie_01.wav")
AddVoice("ZOMBIE DEAD2", "Necrotic contained.", "triage-hl2rp/suppressor/announcekill_zombie_02.wav")
AddVoice("ZOMBIE DEAD3", "Stay dead.", "triage-hl2rp/suppressor/announcekill_zombie_03.wav")
AddVoice("ZOMBIE DEAD4", "Contaminant eliminated.", "triage-hl2rp/suppressor/announcekill_zombie_04.wav")
AddVoice("ZOMBIE DEAD5", "Necrotic is silent.", "triage-hl2rp/suppressor/announcekill_zombie_05.wav")
AddVoice("ITS DEAD", "It's dead.", "triage-hl2rp/suppressor/announcekill_zombie_06.wav")
AddVoice("ZOMBIE DEAD6", "Cleanse successful.", "triage-hl2rp/suppressor/announcekill_zombie_07.wav")
 
 
AddVoice("ALPHA", "Alpha.", "triage-hl2rp/suppressor/calloutcode_alpha_01.wav")
AddVoice("AND", "And.", "triage-hl2rp/suppressor/calloutcode_and_01.wav")
AddVoice("BRAVO", "Bravo.", "triage-hl2rp/suppressor/calloutcode_bravo_01.wav")
AddVoice("CHARLIE", "Charlie.", "triage-hl2rp/suppressor/calloutcode_charlie_01.wav")
AddVoice("DELTA", "Delta.", "triage-hl2rp/suppressor/calloutcode_delta_01.wav")
AddVoice("DASH", "Dash.", "triage-hl2rp/suppressor/calloutcode_dash_01.wav")
AddVoice("ECHO", "Echo.", "triage-hl2rp/suppressor/calloutcode_echo_01.wav")
AddVoice("EIGHT", "Eight.", "triage-hl2rp/suppressor/calloutcode_eight_01.wav")
AddVoice("8", "Eight.", "triage-hl2rp/suppressor/calloutcode_eight_01.wav")
AddVoice("ELEVEN", "Eleven.", "triage-hl2rp/suppressor/calloutcode_eleven_01.wav")
AddVoice("11", "Eleven.", "triage-hl2rp/suppressor/calloutcode_eleven_01.wav")
AddVoice("FIFTY", "Fifty.", "triage-hl2rp/suppressor/calloutcode_fifty_01.wav")
AddVoice("50", "Fifty.", "triage-hl2rp/suppressor/calloutcode_fifty_01.wav")
AddVoice("FIVE", "Five.", "triage-hl2rp/suppressor/calloutcode_five_01.wav")
AddVoice("5", "Five.", "triage-hl2rp/suppressor/calloutcode_five_01.wav")
AddVoice("FOURTY", "Fourty.", "triage-hl2rp/suppressor/calloutcode_forty_01.wav")
AddVoice("FORTY", "Fourty.", "triage-hl2rp/suppressor/calloutcode_forty_01.wav")
AddVoice("40", "Fourty.", "triage-hl2rp/suppressor/calloutcode_forty_01.wav")
AddVoice("FOUR", "Four.", "triage-hl2rp/suppressor/calloutcode_four_01.wav")
AddVoice("4", "Four.", "triage-hl2rp/suppressor/calloutcode_four_01.wav")
AddVoice("HUNDRED", "Hundred.", "triage-hl2rp/suppressor/calloutcode_hundred_01.wav")
AddVoice("NINER", "Niner.", "triage-hl2rp/suppressor/calloutcode_niner_01.wav")
AddVoice("9", "Niner.", "triage-hl2rp/suppressor/calloutcode_niner_01.wav")
AddVoice("NULL", "Null.", "triage-hl2rp/suppressor/calloutcode_null_01.wav")
AddVoice("ONE", "One.", "triage-hl2rp/suppressor/calloutcode_one_01.wav")
AddVoice("1", "One.", "triage-hl2rp/suppressor/calloutcode_one_01.wav")
AddVoice("SECTOR", "Sector.", "triage-hl2rp/suppressor/calloutcode_sector_01.wav")
AddVoice("SEVEN", "Seven.", "triage-hl2rp/suppressor/calloutcode_seven_01.wav")
AddVoice("7", "Seven.", "triage-hl2rp/suppressor/calloutcode_seven_01.wav")
AddVoice("SEVENTY", "Seventy.", "triage-hl2rp/suppressor/calloutcode_seventy_01.wav")
AddVoice("70", "Seventy.", "triage-hl2rp/suppressor/calloutcode_seventy_01.wav")
AddVoice("SIX", "Six.", "triage-hl2rp/suppressor/calloutcode_six_01.wav")
AddVoice("6", "Six.", "triage-hl2rp/suppressor/calloutcode_six_01.wav")
AddVoice("SIXTY", "Sixty.", "triage-hl2rp/suppressor/calloutcode_sixty_01.wav")
AddVoice("60", "Sixty.", "triage-hl2rp/suppressor/calloutcode_sixty_01.wav")
AddVoice("TEN", "Ten.", "triage-hl2rp/suppressor/calloutcode_ten_01.wav")
AddVoice("10", "Ten.", "triage-hl2rp/suppressor/calloutcode_ten_01.wav")
AddVoice("THIRTY", "Thirty.", "triage-hl2rp/suppressor/calloutcode_thirty_01.wav")
AddVoice("30", "Thirty.", "triage-hl2rp/suppressor/calloutcode_thirty_01.wav")
AddVoice("THOUSAND", "Thousand.", "triage-hl2rp/suppressor/calloutcode_thousand_01.wav")
AddVoice("THREE", "Three.", "triage-hl2rp/suppressor/calloutcode_three_01.wav")
AddVoice("3", "Three.", "triage-hl2rp/suppressor/calloutcode_three_01.wav")
AddVoice("TWENTY", "Twenty.", "triage-hl2rp/suppressor/calloutcode_twenty_01.wav")
AddVoice("20", "Twenty.", "triage-hl2rp/suppressor/calloutcode_twenty_01.wav")
AddVoice("TWO", "Two.", "triage-hl2rp/suppressor/calloutcode_two_01.wav")
AddVoice("2", "Two.", "triage-hl2rp/suppressor/calloutcode_two_01.wav")
 
 
AddVoice("", "Alyx.", "triage-hl2rp/suppressor/calloutentity_alyx_01.wav")
AddVoice("ANTICITIZENS", "Anti-citizens.", "triage-hl2rp/suppressor/calloutentity_anticitizens_01.wav")
AddVoice("ANTLION", "Antlion.", "triage-hl2rp/suppressor/calloutentity_antlion_01.wav")
AddVoice("APF", "APF.", "triage-hl2rp/suppressor/calloutentity_apf_01.wav")
AddVoice("BLADEWALL", "Bladewall.", "triage-hl2rp/suppressor/calloutentity_bladewall_01.wav")
AddVoice("COWALL", "Co-wall.", "triage-hl2rp/suppressor/calloutentity_cowall_01.wav")
AddVoice("FRIENDLY", "Friendly.", "triage-hl2rp/suppressor/calloutentity_friendly_01.wav")
AddVoice("HAMMERWALL", "Hammerwall.", "triage-hl2rp/suppressor/calloutentity_hammerwall_01.wav")
AddVoice("HOSTILES", "Hostiles.", "triage-hl2rp/suppressor/calloutentity_hostiles_01.wav")
AddVoice("3 PARASITICS", "Three parasitics.", "triage-hl2rp/suppressor/calloutentity_manyparasitics_01.wav")
AddVoice("NECROTIC", "Necrotic.", "triage-hl2rp/suppressor/calloutentity_necrotic_01.wav")
AddVoice("PARASITIC", "Parasitic.", "triage-hl2rp/suppressor/calloutentity_parasitic_01.wav")
AddVoice("SAFEMAN", "Safeman.", "triage-hl2rp/suppressor/calloutentity_safeman_01.wav")
AddVoice("WALLHAMMER", "Wallhammer.", "triage-hl2rp/suppressor/calloutentity_wallhammer_01.wav")
 
AddVoice("ABOVE", "Above.", "triage-hl2rp/suppressor/calloutlocation_above_01.wav")
AddVoice("APARTMENT", "Apartment.", "triage-hl2rp/suppressor/calloutlocation_apartment_01.wav")
AddVoice("BARRELS", "Barrels.", "triage-hl2rp/suppressor/calloutlocation_barrells_01.wav")
AddVoice("BEHIND", "Behind.", "triage-hl2rp/suppressor/calloutlocation_behind_01.wav")
AddVoice("BELOW", "Below.", "triage-hl2rp/suppressor/calloutlocation_below_01.wav")
AddVoice("BRICKS", "Bricks.", "triage-hl2rp/suppressor/calloutlocation_bricks_01.wav")
AddVoice("BRIDGE", "Bridge.", "triage-hl2rp/suppressor/calloutlocation_bridge_01.wav")
AddVoice("BUILDING", "Building.", "triage-hl2rp/suppressor/calloutlocation_building_01.wav")
AddVoice("CAR", "Car.", "triage-hl2rp/suppressor/calloutlocation_car_01.wav")
AddVoice("CRANE", "Crane.", "triage-hl2rp/suppressor/calloutlocation_crane_01.wav")
AddVoice("DOOR", "Door.", "triage-hl2rp/suppressor/calloutlocation_door_01.wav")
AddVoice("ELEVATOR", "Elevator.", "triage-hl2rp/suppressor/calloutlocation_elevator_01.wav")
AddVoice("FRONT", "Front.", "triage-hl2rp/suppressor/calloutlocation_front_01.wav")
AddVoice("HUT", "Hut.", "triage-hl2rp/suppressor/calloutlocation_hut_01.wav")
AddVoice("PIPES", "Pipes.", "triage-hl2rp/suppressor/calloutlocation_pipes_01.wav")
AddVoice("SHACK", "Shack.", "triage-hl2rp/suppressor/calloutlocation_shack_01.wav")
AddVoice("TOILET", "Toilet.", "triage-hl2rp/suppressor/calloutlocation_toilet_01.wav")
AddVoice("TRAINCAR", "Traincar.", "triage-hl2rp/suppressor/calloutlocation_traincar_01.wav")
AddVoice("TRASH", "Trash.", "triage-hl2rp/suppressor/calloutlocation_trash_01.wav")
AddVoice("TRUCK", "Truck.", "triage-hl2rp/suppressor/calloutlocation_truck_01.wav")
AddVoice("TUNNEL", "Tunnel.", "triage-hl2rp/suppressor/calloutlocation_tunnel_01.wav")
AddVoice("VAN", "Van.", "triage-hl2rp/suppressor/calloutlocation_van_01.wav")
AddVoice("WHEELS", "Wheels.", "triage-hl2rp/suppressor/calloutlocation_wheels_01.wav")
AddVoice("WOODPILE", "Woodpile.", "triage-hl2rp/suppressor/calloutlocation_woodpile_01.wav")
 
 
AddVoice("CLOSING", "Closing on leader. Initiate condition SHADOW.", "triage-hl2rp/suppressor/choreo_22_2000.wav")
 
 
AddVoice("OW ACTIVE HOSTILES", "Overwatch, we have active hostiles. Advise preparations.", "triage-hl2rp/suppressor/combat_idle_012.wav")
AddVoice("TARGET ACTIVE", "Negative, target is still active.", "triage-hl2rp/suppressor/combat_idle_020.wav")
AddVoice("CON ALPHA", "Copy that. Forming condition ALPHA.", "triage-hl2rp/suppressor/combat_idle_030.wav")
AddVoice("CON ALPHA2", "Copy that. Forming condition ALPHA at GRID-NINER-DASH-THREE-SEVEN.", "triage-hl2rp/suppressor/combat_idle_031.wav")
AddVoice("HOLDING FOR", "Holding for advanced directive, over.", "triage-hl2rp/suppressor/combat_idle_040.wav")
AddVoice("RECALIBRATING", "Confirmed, recalibrating.", "triage-hl2rp/suppressor/combat_idle_050.wav")
AddVoice("SETTING UP", "Copy, setting up position.", "triage-hl2rp/suppressor/combat_idle_060.wav")
AddVoice("STILL ACTIVE", "They're still alive.", "triage-hl2rp/suppressor/combat_idle_070.wav")
AddVoice("CC UNDERWAY", "Copy that, contain and control is underway.", "triage-hl2rp/suppressor/combat_idle_080.wav")
AddVoice("RESOLVING", "Resolving", "triage-hl2rp/suppressor/combat_idle_090.wav")
AddVoice("LOCKED AND READY", "10-4, negative on dagger renew - locked and ready.", "triage-hl2rp/suppressor/combat_idle_100.wav")
AddVoice("TAC ADV", "Forming tactical advantage.", "triage-hl2rp/suppressor/combat_idle_110.wav")
AddVoice("STILL HOLDING", "Still holding.", "triage-hl2rp/suppressor/combat_idle_120.wav")
AddVoice("STILL HOLDING2", "Still holding.", "triage-hl2rp/suppressor/combat_idle_121.wav")
AddVoice("HOLDING BIODAT", "Holding for biodat upload.", "triage-hl2rp/suppressor/combat_idle_130.wav")
AddVoice("PREPARING SUNDOWN", "Preparing for sundown.", "triage-hl2rp/suppressor/combat_idle_141.wav")
AddVoice("PREPARE COMMS", "Preparing comms for extended conflict.", "triage-hl2rp/suppressor/combat_idle_150.wav")
AddVoice("NO DAGGERS", "Negative, no daggers needed.", "triage-hl2rp/suppressor/combat_idle_160.wav")
AddVoice("EXTENDING", "Extending conflict duration.", "triage-hl2rp/suppressor/combat_idle_170.wav")
AddVoice("SCANNING BIODATS", "Scanning hostile biodats.", "triage-hl2rp/suppressor/combat_idle_180.wav")
AddVoice("DISREGARDING", "Disregarding last call.", "triage-hl2rp/suppressor/combat_idle_190.wav")
AddVoice("OW 10-9", "Overwatch, ten-niner.", "triage-hl2rp/suppressor/combat_idle_200.wav")
 
 
AddVoice("COVER", "Cover me!", "HLAComVoice/Officer/coverme_01.wav")
AddVoice("COVER2", "Cover!", "HLAComVoice/Officer/coverme_02.wav")
AddVoice("COVER3", "Cover on APF!", "HLAComVoice/Officer/coverme_03.wav")
AddVoice("COVER4", "Need covering fire!", "HLAComVoice/Officer/coverme_04.wav")
AddVoice("COVER5", "Requesting cover at APF!", "HLAComVoice/Officer/coverme_05.wav")
AddVoice("COVER AT", "Cover at...", "HLAComVoice/Officer/coverme_07.wav")
 
 
AddVoice("GRENADE3", "Evade!", "triage-hl2rp/suppressor/danger_grenade_01.wav")
AddVoice("GRENADE2", "Grenade!", "triage-hl2rp/suppressor/danger_grenade_02.wav")
AddVoice("TAKE COVER", "Take cover!", "triage-hl2rp/suppressor/danger_grenade_03.wav")
AddVoice("GRENADE4", "Live grenade.", "triage-hl2rp/suppressor/danger_grenade_04.wav")
AddVoice("GRENADE5", "Bouncer, bouncer!", "triage-hl2rp/suppressor/danger_grenade_05.wav")
AddVoice("GRENADE6", "Grenade, move!", "triage-hl2rp/suppressor/danger_grenade_06.wav")
AddVoice("WATCH OUT", "Watch out!", "triage-hl2rp/suppressor/danger_grenade_08.wav")
AddVoice("GET BACK", "Get back!", "triage-hl2rp/suppressor/danger_grenade_09.wav")
AddVoice("GRENADE7", "Live bouncer, get back!", "triage-hl2rp/suppressor/danger_grenade_10.wav")
 
 
AddVoice("LOF1", "APF, closing.", "triage-hl2rp/suppressor/establishinglof_01.wav")
AddVoice("LOF2", "Switching position.", "triage-hl2rp/suppressor/establishinglof_02.wav")
AddVoice("LOF3", "Fixing viscon.", "triage-hl2rp/suppressor/establishinglof_03.wav")
AddVoice("LOF4", "Holding sightlines.", "triage-hl2rp/suppressor/establishinglof_04.wav")
AddVoice("LOF5", "Realigning to hostile.", "triage-hl2rp/suppressor/establishinglof_05.wav")
AddVoice("LOF6", "Target visual confirmation.", "triage-hl2rp/suppressor/establishinglof_06.wav")
AddVoice("NO VISUAL", "No visual on target. Moving!", "triage-hl2rp/suppressor/establishinglof_08.wav")
AddVoice("LOF8", "Realigning target delta.", "triage-hl2rp/suppressor/establishinglof_09.wav")
AddVoice("STAY THERE", "Stay there!", "triage-hl2rp/suppressor/establishinglof_10.wav")
AddVoice("CHANGING POS1", "Changing position.", "triage-hl2rp/suppressor/establishinglof_11.wav")
AddVoice("CHANGING POS2", "Optimizing location.", "triage-hl2rp/suppressor/establishinglof_12.wav")
AddVoice("CHANGING POS3", "Amending sightlines.", "triage-hl2rp/suppressor/establishinglof_13.wav")
AddVoice("CHANGING POS4", "Problem visual, moving.", "triage-hl2rp/suppressor/establishinglof_14.wav")
AddVoice("CHANGING POS5", "Clearing sightlines.", "triage-hl2rp/suppressor/establishinglof_15.wav")
AddVoice("CONTACT IN", "Contact in three...", "triage-hl2rp/suppressor/establishinglof_17.wav")
AddVoice("EXPOSING", "Exposing primary.", "triage-hl2rp/suppressor/establishinglof_18.wav")
AddVoice("DONT MOVE", "Don't move.", "triage-hl2rp/suppressor/establishinglof_19.wav")
 
 
AddVoice("", "Alyx!", "triage-hl2rp/suppressor/fakeout_calltoalyx_01.wav")
AddVoice("", "Hey, Alyx!", "triage-hl2rp/suppressor/fakeout_calltoalyx_02.wav")
AddVoice("", "Hey Alyx, it's us!", "triage-hl2rp/suppressor/fakeout_calltoalyx_03.wav")
AddVoice("", "Alyx, you there?", "triage-hl2rp/suppressor/fakeout_calltoalyx_04.wav")
AddVoice("", "Alyx!", "triage-hl2rp/suppressor/fakeout_calltoalyx_05.wav")
 
 
AddVoice("TARGET FRIENDLY", "Cease fire, target is friendly.", "triage-hl2rp/suppressor/fakeout_responseceasefire_01.wav")
AddVoice("STANDING DOWN", "Weapons down! Apf, weapons down!", "triage-hl2rp/suppressor/fakeout_responseceasefire_02.wav")
AddVoice("CEASE FIRE", "Cease fire! Cease fire!", "triage-hl2rp/suppressor/fakeout_responseceasefire_03.wav")
AddVoice("", "Alyx is friendly.", "triage-hl2rp/suppressor/fakeout_responseceasefire_04.wav")
AddVoice("", "Stop fire! Alyx is friendly!", "triage-hl2rp/suppressor/fakeout_responseceasefire_05.wav")
 
 
AddVoice("HAHA", "Haha.", "triage-hl2rp/suppressor/fakeout_success_01.wav")
AddVoice("FRIEND GAME", "Friend game effective.", "triage-hl2rp/suppressor/fakeout_success_02.wav")
AddVoice("HOSTILE SCRAMBLED", "Hahaha... hostile is scrambled.", "triage-hl2rp/suppressor/fakeout_success_03.wav")
 
 
AddVoice("FIRING", "Firing.", "triage-hl2rp/suppressor/firing_01.wav")
AddVoice("FIRING2", "Engaging target.", "triage-hl2rp/suppressor/firing_02.wav")
AddVoice("WEAPONS FREE4", "Weapons free.", "triage-hl2rp/suppressor/firing_04.wav")
AddVoice("FIRING4", "APF at primary setpoint.", "triage-hl2rp/suppressor/firing_05.wav")
AddVoice("WEAPONS FREE5", "Open fire, weapons free.", "triage-hl2rp/suppressor/firing_06.wav")
AddVoice("WEAPONS FREE6", "Code Three, maintaining cleanup.", "triage-hl2rp/suppressor/firing_07.wav")
AddVoice("FIRING5", "Cleaning sector.", "triage-hl2rp/suppressor/firing_08.wav")
AddVoice("FIRING6", "Daggers commit on hostile.", "triage-hl2rp/suppressor/firing_09.wav")
AddVoice("PROSECUTING", "Prosecuting.", "triage-hl2rp/suppressor/firing_10.wav")
AddVoice("FIRING7", "Engaged and firing.", "triage-hl2rp/suppressor/firing_110.wav")
AddVoice("FIRING8", "Enforcing stability on primary target in sector.", "triage-hl2rp/suppressor/firing_120.wav")
AddVoice("FIRING9", "Target is in line.", "triage-hl2rp/suppressor/firing_130.wav")
AddVoice("FIRING10", "Target is in line and receiving spikes.", "triage-hl2rp/suppressor/firing_131.wav")
AddVoice("ESCALATING", "Escalating force on primary target.", "triage-hl2rp/suppressor/firing_140.wav")
AddVoice("GOING DOWN3", "They're going down.", "triage-hl2rp/suppressor/firing_150.wav")
AddVoice("GOING DOWN2", "They're going down.", "triage-hl2rp/suppressor/firing_151.wav")
AddVoice("GOING DOWN", "They're going down!", "triage-hl2rp/suppressor/firing_152.wav")
AddVoice("ALMOST OVER2", "Almost over.", "triage-hl2rp/suppressor/firing_160.wav")
AddVoice("ALMOST OVER", "It's almost over!", "triage-hl2rp/suppressor/firing_161.wav")
AddVoice("ALMOST OVER3", "It's almost over.", "triage-hl2rp/suppressor/firing_162.wav")
AddVoice("SENDING SPIKES", "Sending spikes.", "triage-hl2rp/suppressor/firing_170.wav")
AddVoice("SENDING SPIKES2", "Sending all spikes to primary target.", "triage-hl2rp/suppressor/firing_180.wav")
AddVoice("SENDING SPIKES3", "Sending all spikes.", "triage-hl2rp/suppressor/firing_190.wav")
AddVoice("DONT RESIST", "Don't resist.", "triage-hl2rp/suppressor/firing_200.wav")
AddVoice("WH ENGAGED", "Wallhammer, is engaged and firing.", "triage-hl2rp/suppressor/firing_210.wav")
AddVoice("ORDINAL FIRING", "Ordinal is engaged and firing.", "triage-hl2rp/suppressor/firing_220.wav")
AddVoice("APF FIRING", "APF is engaged and firing.", "triage-hl2rp/suppressor/firing_230.wav")
 
 
AddVoice("TARGET FIRE", "Open fire, priority one.", "triage-hl2rp/suppressor/firing_player_01.wav")
AddVoice("ORDINAL FIRE AT", "Ordinal, open fire at...", "triage-hl2rp/suppressor/firing_player_04.wav")
AddVoice("ANTICITIZEN ONE", "Anti-citizen One confirmed, firing.", "triage-hl2rp/suppressor/firing_player_08.wav")
 
 
AddVoice("FLUSHING", "Clearing.", "triage-hl2rp/suppressor/flushing_01.wav")
AddVoice("FLUSHING2", "Distribution on three...", "triage-hl2rp/suppressor/flushing_02.wav")
AddVoice("FLUSHING3", "Flushing sectors.", "triage-hl2rp/suppressor/flushing_03.wav")
AddVoice("FLUSHING4", "Applying pressure. Flare down.", "triage-hl2rp/suppressor/flushing_05.wav")
AddVoice("FLUSHING5", "Flushing hostile.", "triage-hl2rp/suppressor/flushing_06.wav")
AddVoice("FLUSHING6", "Bouncer on last known.", "triage-hl2rp/suppressor/flushing_07.wav")
 
 
AddVoice("EXPOSING", "Exposing.", "triage-hl2rp/suppressor/getback_01.wav")
AddVoice("TAKE COVER", "Take cover!", "triage-hl2rp/suppressor/getback_02.wav")
AddVoice("WATCH OUT", "Watch out!", "triage-hl2rp/suppressor/getback_03.wav")
AddVoice("BOUNCER", "Bouncer, bouncer!", "triage-hl2rp/suppressor/getback_04.wav")
AddVoice("GET DOWN", "Get down!", "triage-hl2rp/suppressor/getback_05.wav")
 
 
AddVoice("HEAR", "Audible, in sector.", "triage-hl2rp/suppressor/hear_suspicious_01.wav")
AddVoice("HEAR2", "Possible contaminant.", "triage-hl2rp/suppressor/hear_suspicious_02.wav")
AddVoice("HEAR3", "Possible hostile active.", "triage-hl2rp/suppressor/hear_suspicious_03.wav")
AddVoice("MOVEMENT AT", "Movement at...", "triage-hl2rp/suppressor/hear_suspicious_04.wav")
AddVoice("SOUND ON", "Sound on.", "triage-hl2rp/suppressor/hear_suspicious_05.wav")
AddVoice("SOUND ON2", "APF sound on, reporting all contaminants.", "triage-hl2rp/suppressor/hear_suspicious_06.wav")
 
 
AddVoice("IDLE1", "Nothing to report.", "triage-hl2rp/suppressor/idle_01.wav")
AddVoice("IDLE2", "Fourteen, eleven, one, fourteen, six, check. Your turn, over.", "triage-hl2rp/suppressor/idle_02.wav")
AddVoice("COPY THAT3", "Copy that.", "triage-hl2rp/suppressor/idle_03.wav")
AddVoice("IDLE3", "Negative movement. Grid SEVEN-DASH-TWO.", "triage-hl2rp/suppressor/idle_04.wav")
AddVoice("RADIALS CLEAR", "Radials clear, over.", "triage-hl2rp/suppressor/idle_06.wav")
AddVoice("HOLDING TRANSMISSION", "Overwatch, holding for transmission.", "triage-hl2rp/suppressor/idle_07.wav")
AddVoice("HOLDING TRANSMISSION2", "Still holding for transmission, over.", "triage-hl2rp/suppressor/idle_08.wav")
AddVoice("SECTOR LOCKDOWN", "Overwatch is confirming sector lockdown. Keep sightlines open, and sound on.", "triage-hl2rp/suppressor/idle_09.wav")
AddVoice("IDLE4", "Outbreak status is code DELTA-SEVEN. Team SUNDOWN is on contact overrun. Copy that.", "triage-hl2rp/suppressor/idle_10.wav")
AddVoice("IDLE5", "Negative... waiting for secondary parameter codes.", "triage-hl2rp/suppressor/idle_11.wav")
AddVoice("UPDATING BIODAT", "Updating biodat... Audibles: Three. Lifevis: Fifteen. Over.", "triage-hl2rp/suppressor/idle_12.wav")
AddVoice("IDLE6", "Roger that. Waiting for contact. Over.", "triage-hl2rp/suppressor/idle_13.wav")
AddVoice("VIROMES", "Viromes inbound. All units advisory, prepare for contact.", "triage-hl2rp/suppressor/idle_14.wav")
AddVoice("IDLE7", "Callout code: TWO-NINER-ZERO... confirmed.", "triage-hl2rp/suppressor/idle_15.wav")
AddVoice("STILL HERE", "Roger that. Still here.", "triage-hl2rp/suppressor/idle_16.wav")
AddVoice("COPY THAT2", "Copy that.", "triage-hl2rp/suppressor/idle_17.wav")
AddVoice("ACCEPT DISSONANCE UPDATE", "Copy, accepted. Update complete in t-minus three seconds. Dissonance resolved.", "triage-hl2rp/suppressor/idle_18.wav")
AddVoice("DISSONANCE UPDATE", "Update is live, acceptance is mandatory.", "triage-hl2rp/suppressor/idle_19.wav")
AddVoice("IDLE8", "Stablization team holding position. Stay alert.", "triage-hl2rp/suppressor/idle_20.wav")
 
 
AddVoice("INJURED", "Requesting stimdose.", "triage-hl2rp/suppressor/injured_01.wav")
AddVoice("INJURED2", "I'm hit.", "triage-hl2rp/suppressor/injured_02.wav")
AddVoice("INJURED3", "Taking damage.", "triage-hl2rp/suppressor/injured_03.wav")
AddVoice("INJURED4", "Soikes effective, applying stimdose.", "triage-hl2rp/suppressor/injured_06.wav")
 
 
AddVoice("HAHA2", "Haha.", "triage-hl2rp/suppressor/laugh_01.wav")
AddVoice("HAHA3", "Haha.", "triage-hl2rp/suppressor/laugh_02.wav")
AddVoice("HAHA4", "Haha.", "triage-hl2rp/suppressor/laugh_03.wav")
AddVoice("HAHA5", "Haha.", "triage-hl2rp/suppressor/laugh_04.wav")
AddVoice("HAHA6", "Haha.", "triage-hl2rp/suppressor/laugh_05.wav")
AddVoice("HAHA7", "Haha.", "triage-hl2rp/suppressor/laugh_06.wav")
 
 
AddVoice("LOST ENEMY", "Contaminant not visible.", "triage-hl2rp/suppressor/lostenemy_01.wav")
AddVoice("REQUESTING LOCATION", "Requesting location.", "triage-hl2rp/suppressor/lostenemy_03.wav")
AddVoice("LOST ENEMY2", "Target lost.", "triage-hl2rp/suppressor/lostenemy_04.wav")
AddVoice("LOST ENEMY3", "Location assist for APF.", "triage-hl2rp/suppressor/lostenemy_05.wav")
AddVoice("LOST ENEMY4", "Negative visual on hostile.", "triage-hl2rp/suppressor/lostenemy_06.wav")
AddVoice("LOST ENEMY5", "Lost sight of contaminant.", "triage-hl2rp/suppressor/lostenemy_07.wav")
AddVoice("LOST ENEMY6", "No viscon, no viscon.", "triage-hl2rp/suppressor/lostenemy_08.wav")
 
 
AddVoice("LOST VISUAL", "Missing hostile, sector unknown.", "triage-hl2rp/suppressor/lostvisual_01.wav")
AddVoice("LOST VISUAL2", "APF requesting target location.", "triage-hl2rp/suppressor/lostvisual_02.wav")
AddVoice("REQUESTING LOCATION2", "Requesting location.", "triage-hl2rp/suppressor/lostvisual_03.wav")
AddVoice("LOST VISUAL3", "Lost sight of hostile.", "triage-hl2rp/suppressor/lostvisual_04.wav")
AddVoice("LOST VISUAL4", "Need location assistance in sector.", "triage-hl2rp/suppressor/lostvisual_07.wav")
AddVoice("NO VISUAL", "No visual. Ordinal - assist.", "triage-hl2rp/suppressor/lostvisual_08.wav")
AddVoice("LOST VISUAL5", "APF, negative on visual.", "triage-hl2rp/suppressor/lostvisual_09.wav")
AddVoice("LOST VISUAL6", "Possible evasion, requesting sightlines.", "triage-hl2rp/suppressor/lostvisual_10.wav")
 
 
AddVoice("TARGET LOST", "Contaminant is quiet, requesting last known sector.", "triage-hl2rp/suppressor/lostvisual_player_01.wav")
AddVoice("VISUAL BLACKOUT", "We have total visual blackout.", "triage-hl2rp/suppressor/lostvisual_player_02.wav")
AddVoice("TARGET LOST2", "Hostile is quiet.", "triage-hl2rp/suppressor/lostvisual_player_03.wav")
AddVoice("TARGET LOST3", "Evasive contaminant - Ordinal, assist.", "triage-hl2rp/suppressor/lostvisual_player_04.wav")
AddVoice("CHECK COVER", "Check cover.", "triage-hl2rp/suppressor/lostvisual_player_05.wav")
AddVoice("CONTACT CHECK", "Contact check.", "triage-hl2rp/suppressor/lostvisual_player_06.wav")
AddVoice("VISUALS LOST", "All visuals lost - eyes on.", "triage-hl2rp/suppressor/lostvisual_player_07.wav")
AddVoice("TARGET LOST4", "All contact quiet. Requesting recon.", "triage-hl2rp/suppressor/lostvisual_player_08.wav")
 
 
AddVoice("PROXIMITY", "Proximity!", "triage-hl2rp/suppressor/nearpanic_02.wav")
AddVoice("ASSIST", "Assist, assist, assist!", "triage-hl2rp/suppressor/nearpanic_04.wav")
 
 
AddVoice("COPY", "Copy.", "triage-hl2rp/suppressor/orderresponse_positive_01.wav")
AddVoice("CAN DO", "APF can do.", "triage-hl2rp/suppressor/orderresponse_positive_05.wav")
AddVoice("ROGER", "Roger.", "triage-hl2rp/suppressor/orderresponse_positive_02.wav")
AddVoice("COPY THAT", "Copy that.", "triage-hl2rp/suppressor/orderresponse_positive_03.wav")
AddVoice("POSITIVE", "Positive.", "triage-hl2rp/suppressor/orderresponse_positive_04.wav")
AddVoice("PROCEEDING", "Proceeding.", "triage-hl2rp/suppressor/orderresponse_positive_04.wav")
AddVoice("AFFIRMATIVE", "Affirmative.", "triage-hl2rp/suppressor/orderresponse_positive_01.wav")
AddVoice("AFFIRMATIVE2", "Affirmative.", "triage-hl2rp/suppressor/orderresponse_positive_06.wav")
 
 
AddVoice("HOLDING", "Holding position.", "triage-hl2rp/suppressor/overwatch_01.wav")
AddVoice("LOCATION LOCKED", "Location locked.", "triage-hl2rp/suppressor/overwatch_02.wav")
AddVoice("WEAPONS READY", "Weapons ready.", "triage-hl2rp/suppressor/overwatch_03.wav")
AddVoice("VISCON LAST", "Viscon on last known position.", "triage-hl2rp/suppressor/overwatch_04.wav")
AddVoice("EYES LAST KNOWN", "Eyes on last known.", "triage-hl2rp/suppressor/overwatch_05.wav")
AddVoice("OBSERVING", "Observing.", "triage-hl2rp/suppressor/overwatch_06.wav")
AddVoice("IN POSITION", "APF, in position.", "triage-hl2rp/suppressor/overwatch_07.wav")
AddVoice("HOLDING2", "Holding focus.", "triage-hl2rp/suppressor/overwatch_08.wav")
AddVoice("STOP SOUND", "Stop sound, stop sound.", "triage-hl2rp/suppressor/overwatch_09.wav")
AddVoice("HOSTILE UNWILLING", "Hostile unwilling, stand by.", "triage-hl2rp/suppressor/overwatch_10.wav")
AddVoice("HOLD", "Hold.", "triage-hl2rp/suppressor/overwatch_11.wav")
AddVoice("WAITING CONTACT", "Waiting for contact.", "triage-hl2rp/suppressor/overwatch_12.wav")
AddVoice("EVALUATING", "Evaluating.", "triage-hl2rp/suppressor/overwatch_13.wav")
AddVoice("AWAITING", "Awaiting problem.", "triage-hl2rp/suppressor/overwatch_14.wav")
AddVoice("WAITING CONTAINMENT", "Waiting for containment.", "triage-hl2rp/suppressor/overwatch_15.wav")
AddVoice("HOLDING3", "APF holding.", "triage-hl2rp/suppressor/overwatch_16.wav")
AddVoice("EYES ON", "APF eyes on.", "triage-hl2rp/suppressor/overwatch_17.wav")
AddVoice("CONT LOCKED", "Contaminant is locked.", "triage-hl2rp/suppressor/overwatch_18.wav")
AddVoice("SECURING EDGE", "APF securing edges.", "triage-hl2rp/suppressor/overwatch_19.wav")
AddVoice("CHECKING EDGES", "Checking all edges.", "triage-hl2rp/suppressor/overwatch_20.wav")
 
 
AddVoice("TARGET HURT", "It's vulnerable.", "triage-hl2rp/suppressor/playerishurt_01.wav")
AddVoice("TARGET HURT2", "Target at odds.", "triage-hl2rp/suppressor/playerishurt_02.wav")
AddVoice("TARGET HURT3", "Target compromised.", "triage-hl2rp/suppressor/playerishurt_03.wav")
AddVoice("MOVE IN2", "Move in, move in!", "triage-hl2rp/suppressor/playerishurt_04.wav")
AddVoice("TARGET HURT4", "Contaminant at low value.", "triage-hl2rp/suppressor/playerishurt_05.wav")
AddVoice("TARGET HURT5", "Hostile is tagged.", "triage-hl2rp/suppressor/playerishurt_06.wav")
AddVoice("TARGET HURT6", "Recall on hostile ASAP.", "triage-hl2rp/suppressor/playerishurt_07.wav")
AddVoice("AMPLIFY WEAPONS", "Amplify weapons on APF.", "triage-hl2rp/suppressor/playerishurt_08.wav")
AddVoice("TARGET HURT7", "Red leak on hostile.", "triage-hl2rp/suppressor/playerishurt_09.wav")
AddVoice("TARGET HURT8", "Possible tag on prime.", "triage-hl2rp/suppressor/playerishurt_10.wav")
AddVoice("TARGET HURT9", "APF effective.", "triage-hl2rp/suppressor/playerishurt_11.wav")
AddVoice("ENDING TARGET", "Ending target one.", "triage-hl2rp/suppressor/playerishurt_13.wav")
 
 
AddVoice("SEARCH FINISHED", "All sectors scanned.", "triage-hl2rp/suppressor/reconnoiter_finish_01.wav")
AddVoice("SEARCH FINISHED2", "Contact is silent.", "triage-hl2rp/suppressor/reconnoiter_finish_02.wav")
AddVoice("CLEAR2", "Sector clear. Requesting stand by.", "triage-hl2rp/suppressor/reconnoiter_finish_03.wav")
AddVoice("CLEAR", "Area clear.", "triage-hl2rp/suppressor/reconnoiter_finish_04.wav")
AddVoice("CLEAR3", "No contact.", "triage-hl2rp/suppressor/reconnoiter_finish_06.wav")
AddVoice("CLEAR4", "Arena secure.", "triage-hl2rp/suppressor/reconnoiter_finish_07.wav")
AddVoice("CLEAR5", "Looks clean.", "triage-hl2rp/suppressor/reconnoiter_finish_08.wav")
AddVoice("CONTACT LOST", "Contact lost, looks clear.", "triage-hl2rp/suppressor/reconnoiter_finish_09.wav")
AddVoice("NOTHING HERE", "Nothing here.", "triage-hl2rp/suppressor/reconnoiter_finish_10.wav")
AddVoice("STAYING SHARP", "Staying sharp, walls up.", "triage-hl2rp/suppressor/reconnoiter_finish_11.wav")
AddVoice("INEFFECTIVE CONTAMINANT", "Ineffective contaminant, requesting standdown.", "triage-hl2rp/suppressor/reconnoiter_finish_12.wav")
AddVoice("STANDBY BRAVO", "Standby for code bravo.", "triage-hl2rp/suppressor/reconnoiter_finish_13.wav")
AddVoice("NOTHING", "Nothing.", "triage-hl2rp/suppressor/reconnoiter_finish_14.wav")
AddVoice("CLEAR6", "Shadow clear.", "triage-hl2rp/suppressor/reconnoiter_finish_15.wav")
AddVoice("END SHADOW", "Request end on condition shadow.", "triage-hl2rp/suppressor/reconnoiter_finish_16.wav")
AddVoice("NOT HERE", "Not here.", "triage-hl2rp/suppressor/reconnoiter_finish_18.wav")
AddVoice("SEARCH FINISHED3", "Location clear. Recall assist.", "triage-hl2rp/suppressor/reconnoiter_finish_19.wav")
AddVoice("SEARCH FINISHED4", "All sectors clear. Recall.", "triage-hl2rp/suppressor/reconnoiter_finish_20.wav")
 
 
AddVoice("SEARCHING", "Viscon processing", "triage-hl2rp/suppressor/reconnoiter_search_01.wav")
AddVoice("SEARCHING2", "Still searching.", "triage-hl2rp/suppressor/reconnoiter_search_02.wav")
AddVoice("SEARCHING3", "Still sweeping.", "triage-hl2rp/suppressor/reconnoiter_search_03.wav")
AddVoice("SHADOW ACTIVE", "Condition shadow active.", "triage-hl2rp/suppressor/reconnoiter_search_06.wav")
AddVoice("SEARCHING4", "Recon in progress.", "triage-hl2rp/suppressor/reconnoiter_search_07.wav")
AddVoice("TARGET SHADOW", "Target is still shadow.", "triage-hl2rp/suppressor/reconnoiter_search_09.wav")
AddVoice("CLEAR MOVING", "Sector clear, advancing.", "triage-hl2rp/suppressor/reconnoiter_search_10.wav")
AddVoice("CLEAR MOVING2", "Null sector, proceeding.", "triage-hl2rp/suppressor/reconnoiter_search_11.wav")
AddVoice("CLEAR MOVING3", "Area cleaned, move in.", "triage-hl2rp/suppressor/reconnoiter_search_12.wav")
AddVoice("SEARCHING5", "Eyes still active.", "triage-hl2rp/suppressor/reconnoiter_search_13.wav")
AddVoice("NOTHING HERE2", "Nothing here.", "triage-hl2rp/suppressor/reconnoiter_search_14.wav")
AddVoice("HOSTILE QUIET", "Hostile is still quiet.", "triage-hl2rp/suppressor/reconnoiter_search_15.wav")
AddVoice("SCAN COMPLETE", "Scan complete. Resuming.", "triage-hl2rp/suppressor/reconnoiter_search_16.wav")
AddVoice("STILL NO VISUAL", "Still no visual.", "triage-hl2rp/suppressor/reconnoiter_search_17.wav")
AddVoice("RADIALS CLEAR", "Radials clear, resume.", "triage-hl2rp/suppressor/reconnoiter_search_18.wav")
 
 
AddVoice("SEARCH START", "Spread it out.", "triage-hl2rp/suppressor/reconnoiter_start_01.wav")
AddVoice("SEARCH START2", "Distributing.", "triage-hl2rp/suppressor/reconnoiter_start_03.wav")
AddVoice("SEARCH START3", "APF out.", "triage-hl2rp/suppressor/reconnoiter_start_04.wav")
AddVoice("SEARCH START4", "Deploying and scanning.", "triage-hl2rp/suppressor/reconnoiter_start_06.wav")
AddVoice("CLEANUP COMMENCING", "Cleanup commencing", "triage-hl2rp/suppressor/reconnoiter_start_07.wav")
AddVoice("SWEEPING HOSTILES", "Sweeping for hostiles.", "triage-hl2rp/suppressor/reconnoiter_start_09.wav")
AddVoice("SWEEPING CONTAMINANT", "Sweeping for contaminant.", "triage-hl2rp/suppressor/reconnoiter_start_10.wav")
AddVoice("SEARCHING6", "Searching shadows", "triage-hl2rp/suppressor/reconnoiter_start_11.wav")
AddVoice("CLOSING ARENA", "Closing arena.", "triage-hl2rp/suppressor/reconnoiter_start_12.wav")
AddVoice("CONTAINMENT PROCEEDING", "Containment proceeding.", "triage-hl2rp/suppressor/reconnoiter_start_13.wav")
AddVoice("REPORTING SIGHTLINES", "Reporting all sightlines.", "triage-hl2rp/suppressor/reconnoiter_start_14.wav")
AddVoice("FORM TARGET IN", "Formation on target in three...", "triage-hl2rp/suppressor/reconnoiter_start_15.wav")
AddVoice("PROCEED EXTRACTION", "Proceeding with hostile extraction.", "triage-hl2rp/suppressor/reconnoiter_start_16.wav")
AddVoice("INITIATE SHADOW", "Initiate condition shadow.", "triage-hl2rp/suppressor/reconnoiter_start_17.wav")
 
 
AddVoice("GO SHARP", "Go sharp, target!", "triage-hl2rp/suppressor/refindenemy_01.wav")
AddVoice("CONTACT AT", "Target contact at...", "triage-hl2rp/suppressor/refindenemy_02.wav")
AddVoice("CONTACT", "Viscon, viscon!", "triage-hl2rp/suppressor/refindenemy_03.wav")
AddVoice("THERE", "There!", "triage-hl2rp/suppressor/refindenemy_04.wav")
AddVoice("CONTACT2", "Viscon, hostile found.", "triage-hl2rp/suppressor/refindenemy_05.wav")
AddVoice("OVER THERE", "Over there!", "triage-hl2rp/suppressor/refindenemy_06.wav")
AddVoice("MOVEMENT", "Movement.", "triage-hl2rp/suppressor/refindenemy_07.wav")
AddVoice("REFIND", "Animal is in the pit.", "triage-hl2rp/suppressor/refindenemy_08.wav")
AddVoice("CONTACT3", "Hostile contact!", "triage-hl2rp/suppressor/refindenemy_09.wav")
AddVoice("GO", "Go go go!", "triage-hl2rp/suppressor/refindenemy_10.wav")
AddVoice("REFIND2", "APF contact, in sector!", "triage-hl2rp/suppressor/refindenemy_11.wav")
AddVoice("CONTACT5", "Hostile live, check radials.", "triage-hl2rp/suppressor/refindenemy_12.wav")
AddVoice("CONTACT6", "Sightline confirmed.", "triage-hl2rp/suppressor/refindenemy_13.wav")
AddVoice("CONTACT7", "Sightline confirmed on prime.", "triage-hl2rp/suppressor/refindenemy_14.wav")
AddVoice("INTERCEPTING", "APF intercepting.", "triage-hl2rp/suppressor/refindenemy_15.wav")
AddVoice("CONTACT CONFIRMED", "Location confirmed. Enforcing stability.", "triage-hl2rp/suppressor/refindenemy_16.wav")
AddVoice("VISCON IN 3", "Visual confirmation on three.", "triage-hl2rp/suppressor/refindenemy_17.wav")
AddVoice("ACTIVE VISUAL AT", "Active visual at...", "triage-hl2rp/suppressor/refindenemy_18.wav")
 
 
AddVoice("RELOADING", "Reloading.", "triage-hl2rp/suppressor/reload_01.wav")
AddVoice("RELOADING2", "Refill on APF.", "triage-hl2rp/suppressor/reload_02.wav")
AddVoice("RELOADING3", "APF low - four... three... two... one!", "triage-hl2rp/suppressor/reload_03.wav")
AddVoice("RELOADING4", "Recharging!", "triage-hl2rp/suppressor/reload_05.wav")
AddVoice("RELOADING5", "Empty!", "triage-hl2rp/suppressor/reload_06.wav")
AddVoice("RELOADING6", "Empty dagger on APF!", "triage-hl2rp/suppressor/reload_07.wav")
AddVoice("RELOADING7", "Provisions low, reloading.", "triage-hl2rp/suppressor/reload_08.wav")
AddVoice("RELOADING8", "Renewing dagger!", "triage-hl2rp/suppressor/reload_09.wav")
 
 
AddVoice("RETREAT", "Ripcord!", "triage-hl2rp/suppressor/retreat_02.wav")
AddVoice("RETREAT2", "Ripcord on APF.", "triage-hl2rp/suppressor/retreat_03.wav")
AddVoice("RETREAT3", "Retreating!", "triage-hl2rp/suppressor/retreat_04.wav")
AddVoice("RETREAT4", "Falling back!", "triage-hl2rp/suppressor/retreat_05.wav")
AddVoice("RETREAT5", "Sector is too hot!", "triage-hl2rp/suppressor/retreat_06.wav")
AddVoice("RETREAT6", "Finding cover!", "triage-hl2rp/suppressor/retreat_07.wav")
AddVoice("RETREAT7", "APF, regrouping!", "triage-hl2rp/suppressor/retreat_08.wav")
AddVoice("RETREAT8", "Sector volatile. Finding shade.", "triage-hl2rp/suppressor/retreat_10.wav")
AddVoice("RETREAT9", "Ripcord, ripcord!", "triage-hl2rp/suppressor/retreat_02.wav")
 
 
AddVoice("MULTIPLE CONTACT", "Secondaries identified.", "triage-hl2rp/suppressor/sees_company_01.wav")
AddVoice("MULTIPLE CONTACT2", "Viscon on multiple unknowns.", "triage-hl2rp/suppressor/sees_company_02.wav")
AddVoice("MULTIPLE CONTACT3", "We have viscon on secondaries.", "triage-hl2rp/suppressor/sees_company_03.wav")
AddVoice("MULTIPLE CONTACT4", "Check silhouettes. Possible multipliers.", "triage-hl2rp/suppressor/sees_company_04.wav")
AddVoice("MULTIPLE CONTACT5", "We have multiple contaminants.", "triage-hl2rp/suppressor/sees_company_05.wav")
 
 
AddVoice("TARGET GRENADES", "Target-One has bouncers.", "triage-hl2rp/suppressor/sees_grenades_01.wav")
AddVoice("TARGET GRENADES2", "Hostile has bouncers. Be alert.", "triage-hl2rp/suppressor/sees_grenades_02.wav")
AddVoice("TARGET GRENADES3", "Contaminant has grenades. Disperse.", "triage-hl2rp/suppressor/sees_grenades_03.wav")
 
 
AddVoice("TARGET RELOADING", "Hostile reloading, dagger advantage.", "triage-hl2rp/suppressor/sees_reloading_01.wav")
AddVoice("TARGET RELOADING2", "Advantage now!", "triage-hl2rp/suppressor/sees_reloading_03.wav")
AddVoice("TARGET RELOADING3", "APF - contaminant is vulnerable!", "triage-hl2rp/suppressor/sees_reloading_04.wav")
AddVoice("", "Alyx reloading, full response active.", "triage-hl2rp/suppressor/sees_reloading_05.wav")
 
 
AddVoice("TARGET UPGRADES", "Spikes boosted on target one.", "triage-hl2rp/suppressor/sees_upgrades_01.wav")
AddVoice("TARGET UPGRADES2", "Overwatch, target one has boosters.", "triage-hl2rp/suppressor/sees_upgrades_02.wav")
AddVoice("TARGET UPGRADES3", "Ordinal, spikes are boosted.", "triage-hl2rp/suppressor/sees_upgrades_03.wav")
AddVoice("TARGET UPGRADES4", "APF - target has illegal spikes.", "triage-hl2rp/suppressor/sees_upgrades_04.wav")
AddVoice("TARGET UPGRADES5", "Boosters active on prime, respond with caution.", "triage-hl2rp/suppressor/sees_upgrades_05.wav")
 
 
AddVoice("MANDOWN", "Overwatch, request reserve action.", "triage-hl2rp/suppressor/squadmemberlost_01.wav")
AddVoice("MANDOWN2", "Overwatch, sector is not secure!", "triage-hl2rp/suppressor/squadmemberlost_02.wav")
AddVoice("MANDOWN3", "Sector niner, outbreak, outbreak, outbreak!", "triage-hl2rp/suppressor/squadmemberlost_03.wav")
AddVoice("MANDOWN4", "Overwatch, sector not controlled.", "triage-hl2rp/suppressor/squadmemberlost_05.wav")
AddVoice("MANDOWN5", "Overwatch, sector is overrun.", "triage-hl2rp/suppressor/squadmemberlost_06.wav")
AddVoice("MANDOWN6", "Overwatch, request SKYSHIELD!", "triage-hl2rp/suppressor/squadmemberlost_07.wav")
AddVoice("MANDOWN7", "Overwatch, recommend new formation.", "triage-hl2rp/suppressor/squadmemberlost_09.wav")
AddVoice("MANDOWN8", "Friendly is down!", "triage-hl2rp/suppressor/squadmemberlost_10.wav")
AddVoice("X IS QUIET", "...is quiet, requesting replacement", "triage-hl2rp/suppressor/squadmemberlost_11.wav")
AddVoice("WE HAVE PROBLEM", "We have a problem.", "triage-hl2rp/suppressor/squadmemberlost_08.wav")
 
 
AddVoice("LAST UNIT", "Overwatch, APF reporting solo.", "triage-hl2rp/suppressor/squadmemberlost_lastman_01.wav")
AddVoice("LAST UNIT2", "Overwatch, APF is last unit, requesting immediate assist.", "triage-hl2rp/suppressor/squadmemberlost_lastman_02.wav")
AddVoice("LAST UNIT3", "Agh, requesting shadow!", "triage-hl2rp/suppressor/squadmemberlost_lastman_03.wav")
AddVoice("LAST UNIT4", "Overwatch, outbreak is uncontained.", "triage-hl2rp/suppressor/squadmemberlost_lastman_04.wav")
AddVoice("", "", "triage-hl2rp/suppressor/squadmemberlost_lastman_05.wav")
AddVoice("LAST UNIT5", "Overwatch, solo contact, excessive hostiles!", "triage-hl2rp/suppressor/squadmemberlost_lastman_06.wav")
AddVoice("LAST UNIT6", "Survival mark deployed.", "triage-hl2rp/suppressor/squadmemberlost_lastman_07.wav")
AddVoice("LAST UNIT7", "Overwatch, requesting extraction on APF.", "triage-hl2rp/suppressor/squadmemberlost_lastman_08.wav")
AddVoice("LAST UNIT8", "Overwatch, APF is last responder.", "triage-hl2rp/suppressor/squadmemberlost_lastman_09.wav")
 
 
AddVoice("LEADER DOWN", "Overwatch, Ordinal is down.", "triage-hl2rp/suppressor/squadmemberlost_leader_01.wav")
AddVoice("LEADER DOWN2", "Ordinal is quiet, requesting assist!", "triage-hl2rp/suppressor/squadmemberlost_leader_02.wav")
AddVoice("LEADER DOWN3", "Ordinal is condition SUNDOWN!", "triage-hl2rp/suppressor/squadmemberlost_leader_03.wav")
AddVoice("", "", "triage-hl2rp/suppressor/squadmemberlost_leader_04.wav")
AddVoice("LEADER DOWN4", "Overwatch, Ordinal omitted, responding!", "triage-hl2rp/suppressor/squadmemberlost_leader_05.wav")
AddVoice("LEADER DOWN5", "Ordinal is silent, administer full response.", "triage-hl2rp/suppressor/squadmemberlost_leader_06.wav")
AddVoice("LEADER DOWN6", "Ordinal is flatline, Ordinal is flatline!", "triage-hl2rp/suppressor/squadmemberlost_leader_07.wav")
 
 
AddVoice("SUPPRESSING", "Suppressing!", "triage-hl2rp/suppressor/suppressing_01.wav")
AddVoice("SUPPRESSING AT", "Suppressing at...", "triage-hl2rp/suppressor/suppressing_02.wav")
AddVoice("SUPPRESSING2", "APF forcing compliance!", "triage-hl2rp/suppressor/suppressing_03.wav")
AddVoice("SUPPRESSIN3", "Barrage on last known!", "triage-hl2rp/suppressor/suppressing_04.wav")
AddVoice("SUPPRESSING AT2", "Antibody-Protection-Force active on...", "triage-hl2rp/suppressor/suppressing_05.wav")
 
 
AddVoice("SPIKES CLOSE", "Spikes close, no damage.", "triage-hl2rp/suppressor/takingfire_01.wav")
AddVoice("TAKING FIRE2", "Missed.", "triage-hl2rp/suppressor/takingfire_02.wav")
AddVoice("TAKING FIRE3", "Target error, take advantage.", "triage-hl2rp/suppressor/takingfire_03.wav")
AddVoice("TAKING FIRE4", "APF - hostile is inaccurate!", "triage-hl2rp/suppressor/takingfire_04.wav")
AddVoice("TAKING FIRE5", "Almost.", "triage-hl2rp/suppressor/takingfire_05.wav")
AddVoice("TAKING FIRE6", "Missed again, taking advantage.", "triage-hl2rp/suppressor/takingfire_07.wav")
AddVoice("TAKING FIRE7", "Target has failed.", "triage-hl2rp/suppressor/takingfire_08.wav")
AddVoice("TAKING FIRE8", "Exercise advantage on hostile.", "triage-hl2rp/suppressor/takingfire_09.wav")
AddVoice("HOSTILE FAILED", "Hostile failed, reforming.", "triage-hl2rp/suppressor/takingfire_10.wav")
AddVoice("TAUNT", "Spikes ineffective. Target is unskilled.", "triage-hl2rp/suppressor/takingfire_11.wav")
 
 
AddVoice("TAUNT2", "Hostile is experiencing extreme panic.", "triage-hl2rp/suppressor/taunt_010.wav")
AddVoice("TAUNT3", "Hostile is overwhelmed.", "triage-hl2rp/suppressor/taunt_020.wav")
AddVoice("TAUNT4", "Target is at low motivation, take advantage.", "triage-hl2rp/suppressor/taunt_030.wav")
AddVoice("TAUNT5", "Target is at low motivation.", "triage-hl2rp/suppressor/taunt_031.wav")
AddVoice("YOU CAN COME OUT", "You can come out now!", "triage-hl2rp/suppressor/taunt_042.wav")
AddVoice("WE CAN HELP YOU2", "Attention hostile target, we can help you, it is safe.", "triage-hl2rp/suppressor/taunt_050.wav")
AddVoice("WE CAN HELP YOU", "We can help you, it is safe.", "triage-hl2rp/suppressor/taunt_051.wav")
AddVoice("TAUNT6", "Suspect is above legal aggression threshold. Taking advantage.", "triage-hl2rp/suppressor/taunt_060.wav")
AddVoice("ESCALATING2", "Proceeding with escalation.", "triage-hl2rp/suppressor/taunt_070.wav")
AddVoice("NON COMPLIANT", "Suspect is non-compliant with code 10-307.", "triage-hl2rp/suppressor/taunt_071.wav")
AddVoice("ESCALATING3", "Code 10-307, proceeding with escalation.", "triage-hl2rp/suppressor/taunt_072.wav")
AddVoice("TAUNT7", "Hostile is hesitating.", "triage-hl2rp/suppressor/taunt_081.wav")
AddVoice("TAUNT8", "Hostile attacks are ineffective, proceeding with containment.", "triage-hl2rp/suppressor/taunt_090.wav")
AddVoice("STANDING DOWN2", "Activating code 10-108, standing down.", "triage-hl2rp/suppressor/taunt_100.wav")
AddVoice("SUSPEND FIRE", "Suspend fire, target is friendly.", "triage-hl2rp/suppressor/taunt_111.wav")
AddVoice("STANDING DOWN3", "Standing down, code 10-40.", "triage-hl2rp/suppressor/taunt_120.wav")
AddVoice("CEASEFIRE ON TARGET", "Ceasing fire, target is non-hostile.", "triage-hl2rp/suppressor/taunt_131.wav")
AddVoice("DO NOT SHOOT", "Copy, do not shoot. Compliance confirmed.", "triage-hl2rp/suppressor/taunt_140.wav")
AddVoice("FRIENDLY2", "Target is friendly.", "triage-hl2rp/suppressor/taunt_150.wav")
AddVoice("FRIENDLY3", "Stand down, target is friendly.", "triage-hl2rp/suppressor/taunt_151.wav")
AddVoice("FRIENDLY4", "All units stand down, target is friendly.", "triage-hl2rp/suppressor/taunt_152.wav")
AddVoice("FRIENDLY5", "Friendly confirmed, cease fire.", "triage-hl2rp/suppressor/taunt_160.wav")
AddVoice("WAIT AND SEE2", "Overwatch, we have a wait and see at grid NINER-DASH-FIVE.", "triage-hl2rp/suppressor/taunt_170.wav")
AddVoice("WAIT AND SEE", "Overwatch, we have a wait and see.", "triage-hl2rp/suppressor/taunt_171.wav")
AddVoice("INJURED7", "Affirmative, target is low value.", "triage-hl2rp/suppressor/taunt_182.wav")
AddVoice("HOSTILE UNAWARE", "Copy that, hostile is unaware and ready for containment.", "triage-hl2rp/suppressor/taunt_191.wav")
AddVoice("INJURED8", "Hostile is showing fatigue. Prepare containment.", "triage-hl2rp/suppressor/taunt_200.wav")
 
 
AddVoice("NEGATIVE", "Negative.", "triage-hl2rp/suppressor/unabletocommence_01.wav")
AddVoice("NEGATORY", "Negatory.", "triage-hl2rp/suppressor/unabletocommence_05.wav")
AddVoice("NO", "No.", "triage-hl2rp/suppressor/unabletocommence_04.wav")
AddVoice("CANT COMPLY", "Can't comply.", "triage-hl2rp/suppressor/unabletocommence_02.wav")
AddVoice("DENIED", "Denied.", "triage-hl2rp/suppressor/unabletocommence_06.wav")
AddVoice("NEGATIVE3", "Overwatch, negative", "triage-hl2rp/suppressor/unabletocommence_03.wav")
AddVoice("NEGATIVE2", "That's a negative.", "triage-hl2rp/suppressor/unabletocommence_07.wav")
 
 
AddVoice("UNDERFIRE", "Spikes confirmation, suppressing active.", "triage-hl2rp/suppressor/underattack_01.wav")
AddVoice("UNDERFIRE2", "Hostile is live.", "triage-hl2rp/suppressor/underattack_02.wav")
AddVoice("UNDERFIRE3", "Contact! Hostile at...", "triage-hl2rp/suppressor/underattack_03.wav")
AddVoice("UNDERFIRE4", "APF is ready to oppress.", "triage-hl2rp/suppressor/underattack_04.wav")
AddVoice("UNDERFIRE5", "We have live contaminants.", "triage-hl2rp/suppressor/underattack_05.wav")
AddVoice("UNDERFIRE6", "Distributing.", "triage-hl2rp/suppressor/underattack_06.wav")
AddVoice("UNDERFIRE7", "Target is hostile, daggers free.", "triage-hl2rp/suppressor/underattack_07.wav")
AddVoice("UNDERFIRE8", "Target oppressing!", "triage-hl2rp/suppressor/underattack_08.wav")
AddVoice("UNDERFIRE9", "Overwatch, we have spikes.", "triage-hl2rp/suppressor/underattack_09.wav")
AddVoice("CONDITION DELTA", "Preparing condition delta.", "triage-hl2rp/suppressor/underattack_10.wav")
AddVoice("TAKING FIRE", "Taking fire.", "triage-hl2rp/suppressor/underattack_11.wav")
AddVoice("EXECUTING RESPONSE", "Executing full response.", "triage-hl2rp/suppressor/underattack_12.wav")
 
 
AddVoice("CHATTER1", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/choreo_22_2004.wav")
AddVoice("CHATTER2", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/Suppressor_radio_idle_01.wav")
AddVoice("CHATTER3", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/Suppressor_radio_idle_02.wav")
AddVoice("CHATTER4", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/Suppressor_radio_idle_03.wav")
AddVoice("CHATTER5", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/Suppressor_radio_idle_04.wav")
AddVoice("CHATTER6", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/Suppressor_radio_idle_05.wav")
AddVoice("CHATTER7", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/Suppressor_radio_idle_06.wav")
AddVoice("CHATTER8", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/Suppressor_radio_idle_07.wav")
AddVoice("CHATTER9", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/Suppressor_radio_idle_08.wav")
AddVoice("CHATTER10", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/29_0010.wav")
AddVoice("CHATTER11", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/29_0011.wav")
AddVoice("CHATTER12", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/29_0012.wav")
AddVoice("CHATTER13", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/29_0013.wav")
AddVoice("CHATTER14", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/30_0019.wav")
AddVoice("CHATTER15", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/30_0021.wav")
AddVoice("CHATTER16", "**Indistinct Radio Chatter**", "HLAComVoice/Chatter/30_0022.wav")

Schema.voices.AddClass("Suppressor", function(ply)
    local char = ply:GetCharacter()
    local class = char:GetClass()
    return (class == CLASS_OTA_SUPPRESSOR)
end)
